- platform: template
  switches:
    dafang_living_room_status:
      friendly_name: Dafang Living Room motion Status
      value_template: "{{ is_state('sensor.dafang_living_room_status_scrape', 'ACTIVE') }}"
      turn_on:
        service: shell_command.dafang_living_room_active
      turn_off:
        service: shell_command.dafang_living_room_pause

- platform: mqtt
  name: "DaFang Living Room RTSP"
  state_topic: "LivingRoom/DaFang/status"
  value_template: '{{ value_json["RTSP-Server"] }}'
  command_topic: "LivingRoom/DaFang/set"
  payload_on: "h264_noseg_start"
  payload_off: "rtsp_stop"
  optimistic: false

- platform: mqtt
  name: "Dafang Living Room Blue LED"
  state_topic: "LivingRoom/DaFang/status"
  value_template: '{{ value_json.LEDs.Blue }}'
  command_topic: "LivingRoom/DaFang/set"
  payload_on: "blue_led_on"
  payload_off: "blue_led_off"
  optimistic: false

- platform: mqtt
  name: "Dafang Living Room Yellow LED"
  state_topic: "LivingRoom/DaFang/status"
  value_template: '{{ value_json.LEDs.Yellow }}'
  command_topic: "LivingRoom/DaFang/set"
  payload_on: "yellow_led_on"
  payload_off: "yellow_led_off"
  optimistic: false


- platform: template
  switches:
    dafang_kitchen_status:
      friendly_name: Dafang Kitchen motion Status
      value_template: "{{ is_state('sensor.dafang_kitchen_status_scrape', 'ACTIVE') }}"
      turn_on:
        service: shell_command.dafang_kitchen_active
      turn_off:
        service: shell_command.dafang_kitchen_pause

- platform: mqtt
  name: "DaFang Kitchen RTSP"
  state_topic: "Kitchen/DaFang/status"
  value_template: '{{ value_json["RTSP-Server"] }}'
  command_topic: "Kitchen/DaFang/set"
  payload_on: "h264_noseg_start"
  payload_off: "rtsp_stop"
  optimistic: false

- platform: mqtt
  name: "Dafang Kitchen Blue LED"
  state_topic: "Kitchen/DaFang/status"
  value_template: '{{ value_json.LEDs.Blue }}'
  command_topic: "Kitchen/DaFang/set"
  payload_on: "blue_led_on"
  payload_off: "blue_led_off"
  optimistic: false

- platform: mqtt
  name: "Dafang Kitchen Yellow LED"
  state_topic: "Kitchen/DaFang/status"
  value_template: '{{ value_json.LEDs.Yellow }}'
  command_topic: "Kitchen/DaFang/set"
  payload_on: "yellow_led_on"
  payload_off: "yellow_led_off"
  optimistic: false



- platform: template
  switches:
    cctv_garage_status:
      friendly_name: CCTV Garage motion Status
      value_template: "{{ is_state('sensor.cctv_garage_status_scrape', 'ACTIVE') }}"
      turn_on:
        service: shell_command.cctv_garage_active
      turn_off:
        service: shell_command.cctv_garage_pause
