- platform: rfxtrx
  # automatic_add: True
  signal_repetitions: 2
  devices:
    0A14001E01010404000070:
      name: Dehumidifier
    0A14002201010402000070:
      name: Kitchen TV
    0A14002301010403000070:
      name: LWRF Socket 3
    0B1101020000000102000070:
      name: LWRF Socket Xmas
    0a1400bef4ff6201010070:
      name: LWRF Remote 1
      fire_event: true
    0a1400c0f4ff6202010070:
      name: LWRF Remote 2
      fire_event: true
    0a1400c1f4ff6203010070:
      name: LWRF Remote 3
      fire_event: true
    09130006131408015e70:
      name: Alarm Siren 1
      fire_event: true
      # data_bits: 4
      # command_on: 0x8
      # command_off: 0x2
    '09130008131402016070':
      name: Alarm Siren 2
      fire_event: true
      # data_bits: 4
      # command_on: 0x2
      # command_off: 0x8
