- platform: template
  switches:
    dafang_living_room_status:
      friendly_name: Dafang Living Room motion Status
      value_template: "{{ is_state('sensor.dafang_living_room_status_scrape', 'ACTIVE') }}"
      turn_on:
        service: shell_command.dafang_living_room_active
      turn_off:
        service: shell_command.dafang_living_room_pause

- platform: template
  switches:
    dafang_living_room_rtsp_status:
      friendly_name: Dafang Living Room motion RTSP Status
      value_template: "{{ is_state('sensor.dafang_living_room_rtsp_status_scrape', 'f') }}"
      turn_on:
        service: shell_command.dafang_living_room_start_rtsp
      turn_off:
        service: shell_command.dafang_living_room_stop_rtsp


- platform: template
  switches:
    dafang_living_room_blue_led:
      friendly_name: Dafang Living Room motion Blue LED
      value_template: "{{ is_state('sensor.dafang_living_room_blue_led_status_scrape', '\n0\n') }}"
      turn_on:
        service: shell_command.dafang_living_room_blue_led_on
      turn_off:
        service: shell_command.dafang_living_room_blue_led_off

- platform: template
  switches:
    dafang_living_room_yellow_led:
      friendly_name: Dafang Living Room motion Yellow LED
      value_template: "{{ is_state('sensor.dafang_living_room_yellow_led_status_scrape', '\n0\n') }}"
      turn_on:
        service: shell_command.dafang_living_room_yellow_led_on
      turn_off:
        service: shell_command.dafang_living_room_yellow_led_off