- platform: mqtt
  state_topic: 'domotigatx/CurrentCost/value1'
  name: 'CurrentCost Power'
  unit_of_measurement: 'Wh'
  value_template: '{{value | int}}'

- platform: mqtt
  state_topic: 'domotigatx/CurrentCost/value4'
  name: 'CurrentCost Temperature'
  unit_of_measurement: '°C'

- platform: mqtt
  state_topic: 'domotigatx/IAMCC/value1'
  name: 'Dehumidifier Power'
  unit_of_measurement: 'Wh'

