- platform: mqtt
  state_topic: "owntracks/ha/lolos_iphone"
  name: "Lolo iPhone"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

- platform: mqtt
  state_topic: "owntracks/zevsmpjl/Div_iPhone"
  name: "Div"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

- platform: mqtt
  state_topic: "owntracks/ha/iPad"
  name: "iPad"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'