- platform: mjpeg
  mjpeg_url: http://192.168.0.24:8082
  name: 'Front'
- platform: mjpeg
  mjpeg_url: http://192.168.0.24:8081
  name: 'FrontHD'
- platform: mjpeg
  mjpeg_url: http://192.168.0.24:8084
  name: 'Living Room'
- platform: mjpeg
  mjpeg_url: http://192.168.0.24:8085
  name: 'Kitchen'
- platform: mjpeg
  mjpeg_url: http://192.168.0.24:8083
  name: 'Garage'


# - platform: ffmpeg
  # input: !secret cctv_url_front
  # name: 'Front'
# - platform: ffmpeg
  # input: !secret cctv_url_living_room
  # name: 'Living Room'
# - platform: ffmpeg
  # input: !secret cctv_url_kitchen
  # name: Kitchen
# - platform: ffmpeg
  # input: !secret cctv_url_garage
  # name: Garage

- platform: generic
  name: 'Lolo'
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.ha_lolos_iphone.attributes.latitude }},{{ states.device_tracker.ha_lolos_iphone.attributes.longitude }}&zoom=15&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:L%7C{{ states.device_tracker.ha_lolos_iphone.attributes.latitude }},{{ states.device_tracker.ha_lolos_iphone.attributes.longitude }}&markers=color:red%7Clabel:D%7C{{ states.device_tracker.ha_div_iphone.attributes.latitude }},{{ states.device_tracker.ha_div_iphone.attributes.longitude }}
  limit_refetch_to_url_change: true
- platform: generic
  name: 'Div'
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.ha_div_iphone.attributes.latitude }},{{ states.device_tracker.ha_div_iphone.attributes.longitude }}&zoom=15&size=500x500&maptype=roadmap&markers=color:red%7Clabel:D%7C{{ states.device_tracker.ha_div_iphone.attributes.latitude }},{{ states.device_tracker.ha_div_iphone.attributes.longitude }}&markers=color:blue%7Clabel:L%7C{{ states.device_tracker.ha_lolos_iphone.attributes.latitude }},{{ states.device_tracker.ha_lolos_iphone.attributes.longitude }}
  limit_refetch_to_url_change: true
- platform: generic
  name: YrForecastCrawley
  still_image_url: https://www.yr.no/place/United_Kingdom/England/Maidenbower/meteogram.svg
  content_type: 'image/svg+xml'
- platform: generic
  name: YrForecastWeybridge
  still_image_url: https://www.yr.no/place/United_Kingdom/England/Weybridge/meteogram.svg
  content_type: 'image/svg+xml'