- platform: mjpeg
  mjpeg_url: http://192.168.0.24:8081
  name: 'Front'
- platform: mjpeg
  mjpeg_url: http://192.168.0.24:8084
  name: 'Living Room'
- platform: mjpeg
  mjpeg_url: http://192.168.0.24:8083
  name: 'Garage'
- platform: generic
  name: 'Lolo'
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.zevsmpjl_lolo_iphone.attributes.latitude }},{{ states.device_tracker.zevsmpjl_lolo_iphone.attributes.longitude }}&zoom=15&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:L%7C{{ states.device_tracker.zevsmpjl_lolo_iphone.attributes.latitude }},{{ states.device_tracker.zevsmpjl_lolo_iphone.attributes.longitude }}&markers=color:red%7Clabel:D%7C{{ states.device_tracker.zevsmpjl_div_iphone.attributes.latitude }},{{ states.device_tracker.zevsmpjl_div_iphone.attributes.longitude }}
  limit_refetch_to_url_change: true
- platform: generic
  name: 'Div'
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.zevsmpjl_div_iphone.attributes.latitude }},{{ states.device_tracker.zevsmpjl_div_iphone.attributes.longitude }}&zoom=15&size=500x500&maptype=roadmap&markers=color:red%7Clabel:D%7C{{ states.device_tracker.zevsmpjl_div_iphone.attributes.latitude }},{{ states.device_tracker.zevsmpjl_div_iphone.attributes.longitude }}&markers=color:blue%7Clabel:L%7C{{ states.device_tracker.zevsmpjl_lolo_iphone.attributes.latitude }},{{ states.device_tracker.zevsmpjl_lolo_iphone.attributes.longitude }}
  limit_refetch_to_url_change: true
