homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 63
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  customize: !include_dir_merge_named customizations
  customize_glob:
    "sensor.*":
      show_last_changed: true
      custom_ui_state_card: state-card-custom-ui
    "binary_sensor.*":
      show_last_changed: true
      custom_ui_state_card: state-card-custom-ui


# Show links to resources in log and front end
#introduction:
recorder:
  db_url: !secret db_url
  purge_interval: 0

customizer:
  custom_ui: local

# Enables the front end
frontend: 
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html

enable_debug:

config:

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.0.0/24


# Checks for available updates
updater:
  include_used_components: True

# Maps
map:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - automation

# View all events in a logbook
logbook:

# Logging level
logger:
  default: error
  logs:
    homeassistant.components.http: warning
    homeassistant.components.camera: error
    requests.packages.urllib3: critical
    requests.packages.urllib3.connectionpool: critical
    miio.device: critical
    homeassistant.components.sensor.sky_hd_status: critical

#    homeassistant.components.rfxtrx: debug

#Track the sun
sun:


alert: !include_dir_merge_named alerts
automation: !include_dir_merge_list automation
binary_sensor: !include_dir_merge_list binary_sensors
camera: !include cameras.yaml
device_tracker: !include device_tracker.yaml
google_assistant: !include Google_Assistant.yaml
group: !include_dir_merge_named groups
#history_graph: !include_dir_merge_named history_graph
input_datetime: !include_dir_merge_named input_datetime
input_select: !include_dir_merge_named input_select
input_number: !include_dir_merge_named input_number
input_text: !include_dir_merge_named input_text
input_boolean: !include_dir_merge_named input_boolean
ios: !include iOS.yaml
light: !include_dir_merge_list lights
notify: !include notify.yaml
# rest_command: !include_dir_merge_named rest
scene: !include_dir_merge_named scenes
script: !include_dir_merge_named scripts
shell_command: !include_dir_merge_named shell_commands
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
zone: !include zones.yaml



ifttt:
  key: !secret ifttt_key

vacuum:
- platform: xiaomi_miio
  name: 'Mi Robot Vacuum'
  host: 192.168.0.18
  token: !secret xiaomi_token

mqtt:
  client_id: home-assistant-1
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_password

tts:
  - platform: google
    # cache: true
    # cache_dir: /tts


media_player:
  - platform: cast
  # Google Home Mini
  - platform: cast
    host: 192.168.0.10
  # Kitchen Cast
  - platform: cast
    host: 192.168.0.12
  # Conservatory Cast
  - platform: cast
    host: 192.168.0.13
  # Mi Box
  - platform: cast
    host: 192.168.0.28
  - platform: kodi
    host: 192.168.0.28
  - platform: cast
    host: 192.168.0.26
  - platform: onkyo
    host: 192.168.0.26
    name: Onkyo TX-NR656
    sources:
      video6: 'Main PC'
      bluray: 'Blu-Ray'
      video2: 'Sky'
      network: 'ChromeCast'
      tv: 'TV'
      strm-box: 'Stream-Box'
    zone2: true
  - platform: panasonic_viera
    host: 192.168.0.27
  - platform: mpd
    host: 192.168.0.21
    port: 6600
    name: MPD RPi Zero W

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1XETWB5-if00-port0

google:
  client_id: !secret GCal_ID
  client_secret: !secret GCal_Secret

counter:
  iosbadgecount:
    initial: 0
    step: 1
    name: iOS Badge Count
    icon: mdi:numeric-1-box

ffmpeg:
  # ffmpeg_bin: /usr/bin/avconv