homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 192.168.0.0/24
 # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 63
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  customize: !include_dir_merge_named customizations


config:
default_config:


#Config Split
alert: !include_dir_merge_named alerts
automation: !include_dir_merge_list automation
binary_sensor: !include_dir_merge_list binary_sensors
camera: !include cameras.yaml
device_tracker: !include device_tracker.yaml
google_assistant: !include Google_Assistant.yaml
group: !include_dir_merge_named groups
influxdb: !include influxdb.yaml
input_datetime: !include_dir_merge_named input_datetime
input_select: !include_dir_merge_named input_select
input_number: !include_dir_merge_named input_number
input_text: !include_dir_merge_named input_text
input_boolean: !include_dir_merge_named input_boolean
ios: !include iOS.yaml
light: !include_dir_merge_list lights
media_player: !include media_player/media_player.yaml
mobile_app: !include iOS.yaml
notify: !include notify.yaml
scene: !include_dir_merge_named scenes
script: !include_dir_merge_named scripts
shell_command: !include_dir_merge_named shell_commands
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
zone: !include zones.yaml


alarm_control_panel:
  - platform: manual
    name: Alarm
    code: !secret alarm_code
    pending_time: 30

bmw_connected_drive:
  220d:
    username: !secret bmw_connected_drive_username
    password: !secret bmw_connected_drive_password
    region: "rest_of_world"

counter:
  iosbadgecount:
    initial: 0
    step: 1
    name: iOS Badge Count
    icon: mdi:numeric-1-box

# Custom Updater: https://github.com/custom-components/custom_updater
#Life360 Device Tracker: https://github.com/pnbruckner/homeassistant-config/blob/master/docs/custom_updater.md
custom_updater:
  track:
    - cards
    - components
    - python_scripts
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
  component_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
  python_script_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/python_scripts.json

discovery:

ffmpeg:

# Enables the front end
frontend: 

google:
  client_id: !secret GCal_ID
  client_secret: !secret GCal_Secret

# googlehome:
  # devices:
    # - host: 192.168.0.9
    # - host: 192.168.0.10

# Enables support for tracking state changes over time.
history:
  # exclude:
    # domains:
      # - automation

http:
  base_url: !secret base_url
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
  ip_ban_enabled: false
  login_attempts_threshold: 3

ifttt:
  key: !secret ifttt_key


life360:
  accounts:
    - username: !secret life360_username
      password: !secret life360_password
  driving_speed: 18
  interval_seconds: 10
  max_gps_accuracy: 200
  max_update_wait:
    minutes: 45
  show_as_state:
    - driving
    - moving
  warning_threshold: 2
  error_threshold: 3
  prefix: ''

# View all events in a logbook
logbook:

# Logging level
# enable_debug:
logger:
  default: error
  logs:
    # homeassistant.components.http: warning
    # homeassistant.components.camera: error
    # requests.packages.urllib3: critical
    # requests.packages.urllib3.connectionpool: critical
    miio.device: critical
    # homeassistant.components.sensor.sky_hd_status: critical
    # homeassistant.components.switch.rest: critical
    # homeassistant.components.rfxtrx: debug
    homeassistant.helpers.entity: critical
    homeassistant.components.scrape: critical
    homeassistant.components.rest: critical
    homeassistant.components.waze_travel_time: critical
    # Lolo bedside light
    # homeassistant.components.xiaomi_miio.light: critical
    # homeassistant.components.light.lolo_bedside_light: critical
    # homeassistant.components.light: critical
    # homeassistant.components.miio.device: critical
    # homeassistant.components.miio: critical


lovelace:
  mode: yaml

map:

mqtt:
  client_id: home-assistant-1
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

person:
  - name: Laurent
    id: laurent
    user_id: !secret ha_lolo_user_id
    device_trackers:
      - device_tracker.lolos_iphone
      - device_tracker.laurent_mah_iphone_5s
      - device_tracker.lolosiphone
      - device_tracker.laurent
  - name: Div
    id: divashni
    user_id: !secret ha_div_user_id
    device_trackers:
      - device_tracker.divashni
      - device_tracker.div_iphone
      - device_tracker.diviphone

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1XETWB5-if00-port0

recorder:
  db_url: !secret db_url

ssdp:

# stream:

sun:

system_health:

tts:
  - platform: google_translate
    service_name: google_say
    language: 'en-uk'

tuya:
  username: !secret tuya_user
  password: !secret tuya_password
  country_code: 44

# Checks for available dates
updater:
  include_used_components: True

vacuum:
- platform: xiaomi_miio
  name: 'Mi Robot Vacuum'
  host: 192.168.0.18
  token: !secret xiaomi_token_vacuum

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - mac: !secret xiaomi_aqara_mac
      key: !secret xiaomi_aqara_password
      host: 192.168.0.5

zeroconf:

# zha:
  # usb_path: /dev/ttyACM0
  # usb_path: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1963360-if00
  # database_path: /config/zigbee.db
  # radio_type: deconz