# - platform: xiaomi
  # host: 192.168.0.1
  # password: !secret xiaomi_router_password

- platform: owntracks
  max_gps_accuracy: 200
  waypoints: True
  waypoint_whitelist:
    - ha

- platform: mqtt
  devices:
    lolo: 'location/lolo'
    div: 'location/div'

- platform: google_maps
  username: !secret Google_Maps_Location_Sharing_User
  password: !secret Google_Maps_Location_Sharing_Password

- platform: tile
  username: !secret tile_user
  password: !secret tile_password