  version: '3'
  services:

    influxdb:
      image: index.docker.io/influxdb:latest
      container_name: influxdb
      ports:
        - "8086:8086"
      volumes:
        - /NAS/influxdb:/var/lib/influxdb
      restart: always

    grafana:
      image: index.docker.io/grafana/grafana:latest
      container_name: grafana
      ports:
        - "3000:3000"
      volumes:
        - /NAS/grafana:/var/lib/grafana
      links:
        - influxdb
      restart: always

    homeassistant:
      container_name: ha
      image: homeassistant/home-assistant:0.101.3
      volumes:
        - /home/cctv/docker_ha:/config
        - /etc/localtime:/etc/localtime:ro
        - /home/cctv/docker_ha/shell_scripts:/shell_scripts:ro
      devices:
        - /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1XETWB5-if00-port0:/dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1XETWB5-if00-port0
      depends_on:
        - influxdb
        - zigbee2mqtt
      restart: always
      network_mode: host


    zigbee2mqtt:
      container_name: zigbee2mqtt
      image: koenkk/zigbee2mqtt
      volumes:
        - /home/cctv/zigbee2mqtt/data:/app/data
        # - /home/cctv/zigbee2mqtt/zigbee-shepherd-converters:/app/node_modules/zigbee-shepherd-converters
      devices:
        - /dev/ttyACM0:/dev/ttyACM0
      restart: always
      network_mode: host