title: Home
resources:
    #Kiosk mode for Alarm panel https://gist.github.com/ciotlosm/1f09b330aa5bd5ea87b59f33609cc931
  - url: /local/kiosk.js?v=1.1
    type: js
    #https://github.com/thomasloven/lovelace-card-tools
  - url: /local/card-tools.js?track=true
    type: js
    # fold-entity https://github.com/thomasloven/lovelace-fold-entity-row
  - url: /local/fold-entity-row.js?track=true
    type: js
    #auto-entities  https://github.com/thomasloven/lovelace-auto-entities
  - url: /local/auto-entities.js?track=true
    type: js
    #List entities in a group https://github.com/ciotlosm/custom-lovelace/tree/master/group-card
  # - url: /local/group-card.js
    # type: js
    #Mini media player https://github.com/kalkih/mini-media-player
  - url: /local/mini-media-player-bundle.js
    type: module
    #Vertical Stack https://github.com/custom-cards/vertical-stack-in-card
  - url: /local/vertical-stack-in-card.js
    type: js
    #Swiper Card https://community.home-assistant.io/t/lovelace-swiper-card/72447
    # https://github.com/bramkragten/custom-ui/tree/master/swipe-card
  # - url: /local/custom-lovelace/swipe-card/swipe-card.js?v=1.1.0
    # type: module
    # https://github.com/custom-cards/tracker-card
  - url: /local/tracker-card.js?track=true
    type: module
    # Fully Kiosk https://github.com/thomasloven/lovelace-fullykiosk
  - url: /local/lovelace-fullykiosk.js
    type: js
  - url: /local/kiosk-config.js
    type: js
views:
  - !include /config/lovelace_views/alarm.yaml
  - !include /config/lovelace_views/home.yaml
  - !include /config/lovelace_views/media.yaml
  - !include /config/lovelace_views/living_room.yaml
  - !include /config/lovelace_views/kitchen.yaml
  - !include /config/lovelace_views/entrance.yaml
  - !include /config/lovelace_views/conservatory.yaml
  - !include /config/lovelace_views/staircase.yaml
  - !include /config/lovelace_views/main_bedroom.yaml
  - !include /config/lovelace_views/kiaan_bedroom.yaml
  - !include /config/lovelace_views/cctv.yaml
  - !include /config/lovelace_views/automations.yaml
  - !include /config/lovelace_views/server.yaml
  - !include /config/lovelace_views/server_stats.yaml
  - !include /config/lovelace_views/car.yaml
  - !include /config/lovelace_views/garage.yaml