title: Automation
background: url("/local/calendar-check.png") fixed
icon: mdi:calendar-check
cards:
  - type: custom:auto-entities
    card:
      type: custom:fold-entity-row
      head:
        type: section
        label: All Automations
      open: false
    filter:
      include:
        - entity_id: "automation.*"

  - type: custom:home-feed-card
    title: Automations Activity Feed
    show_empty: true
    more_info_on_tap: true
    max_item_count: 99
    entities:
      - automation.17track_updates
      - automation.alarm_alarm_triggered
      - automation.alarm_arm_alarm_from_ios_notification
      - automation.alarm_armed
      - automation.alarm_arming_when_windows_left_open
      - automation.alarm_disarm_alarm_from_ios_notification
      - automation.alarm_disarm_alarm_when_reaching_home_from_ios_notification
      - automation.alarm_disarming
      - automation.alarm_fire_alarm
      - automation.alarm_notify_to_arm_when_leaving_home_unarmed
      - automation.alarm_pending_arming
      - automation.alarm_pending_siren
      - automation.alarm_re_arm_alarm_after_unplanned_reboot
      - automation.alarm_remote_arm
      - automation.alarm_remote_disarm
      - automation.alarm_start_charging_fire_7
      - automation.alarm_stop_charging_fire_7
      - automation.alarm_switch_everything_off_when_we_leave_home
      - automation.alarm_trigger_while_armed_away
      - automation.alert_currentcost_lost_off
      - automation.alert_currentcost_lost_on
      - automation.alert_fire_7_lost_off
      - automation.alert_fire_7_lost_on
      - automation.alert_pi_kitchen_lost_off
      - automation.alert_pi_kitchen_lost_on
      - automation.alert_ram_above_90_off
      - automation.alert_ram_above_90_on
      - automation.alert_temperature_loft_lost_off
      - automation.alert_temperature_loft_lost_on
      - automation.alert_temperature_upstairs_lost_off
      - automation.alert_temperature_upstairs_lost_on
      - automation.all_lights_off
      - automation.all_lights_off_sunrise
      - automation.bathroom_turn_fan_off_when_r_75
      - automation.bathroom_turn_fan_on_when_r_75
      - automation.bmw_ios_notification_car_unlocked
      - automation.bmw_ios_notification_lock_car
      - automation.bmw_ventilate_the_car_from_ios_notification
      - automation.bmw_ventilate_when_temp_above_20
      - automation.bmw_windows_doors_left_open
      - automation.build_weather_greeting_ifttt
      - automation.cctv_activate_motion_we_leave_home
      - automation.cctv_deactivate_motion_we_reach_home
      - automation.cctv_email_when_back_cctv_disk_error
      - automation.cctv_email_when_back_cctv_sd_card_full
      - automation.cctv_email_when_front_cctv_disk_error
      - automation.cctv_email_when_front_cctv_sd_card_full
      - automation.cctv_email_when_side_cctv_disk_error
      - automation.cctv_email_when_side_cctv_sd_card_full
      - automation.cctv_garage_cctv_conservatory_connection_lost
      - automation.cctv_garage_cctv_motion_connection_lost
      - automation.cctv_kitchen_cctv_motion_connection_lost
      - automation.cctv_living_room_cctv_motion_connection_lost
      - automation.cctv_set_dafang_blue_led_on
      - automation.cctv_set_dafang_yellow_led_on
      - automation.chromecast_set_radio_volume
      - automation.chromecast_set_speakers_station
      - automation.conservatory_led_lights_on_pir
      - automation.conservatory_lights_dimmed_off_pir
      - automation.conservatory_lights_off_pir
      - automation.conservatory_lights_on_pir
      - automation.decrease_counter_with_alert_to_idle
      - automation.dehumidifier_tank_is_full
      - automation.doorbell_notification
      - automation.edimax_battery_is_charged_turning_edimax_off
      - automation.edimax_start_charging_battery
      - automation.failed_login_attempt_notification
      - automation.flash_alert
      - automation.ga_play_absolute_cr_radio
      - automation.ga_play_absolute_radio
      - automation.ga_play_chill_radio
      - automation.ga_play_radio_fiji_two_radio
      - automation.ga_play_radio_navtarang
      - automation.ga_play_rtl2_radio
      - automation.hallway_light_off_2_min_after_opening_main_door
      - automation.hallway_light_on_when_opening_main_door
      - automation.hass_nightly_restart
      - automation.hass_start_radiostream_scrape
      - automation.hass_start_sound
      - automation.hass_start_xmas_setup
      - automation.hass_stop_motion_detection
      - automation.hass_update_available_notification
      - automation.hasspodcast_update_available
      - automation.holiday_end
      - automation.holiday_living_room
      - automation.holiday_start
      - automation.holiday_upstairs_off
      - automation.holiday_upstairs_on
      - automation.house_number_off
      - automation.house_number_on
      - automation.keep_google_home_alive
      - automation.kiaan_night_light_off_weedays
      - automation.kiaan_night_light_off_weekend
      - automation.kiaan_night_light_sleep
      - automation.kiaan_night_light_wake_phase1_weekdays
      - automation.kiaan_night_light_wake_phase1_weekend
      - automation.kiaan_night_light_wake_phase2
      - automation.kitchen_lights_dimmed_off_pir
      - automation.kitchen_lights_off_pir
      - automation.kitchen_lights_on_pir
      - automation.kitchen_tv_off_pir
      - automation.kitchen_tv_on_pir
      - automation.living_room_main_light_dimmed
      - automation.living_room_main_light_dimmed_off_pir
      - automation.living_room_main_light_off_pir
      - automation.living_room_main_light_on_pir
      - automation.living_room_main_light_undimmed
      - automation.location_div
      - automation.location_lolo
      - automation.lwrf_remote_1_off
      - automation.lwrf_remote_1_on
      - automation.lwrf_remote_2_on
      - automation.lwrf_remote_3_off
      - automation.lwrf_remote_3_on
      - automation.mark_dehumidifier_tank_as_not_full
      - automation.mark_lwrf_socket_as_on_if_currentcost_on
      - automation.mute_kello_alarms
      - automation.nest_remove_away_mode
      - automation.nest_set_away_mode
      - automation.nest_set_eta
      - automation.notify_ios_app
      - automation.play_good_morning
      - automation.play_radio_on_kello
      - automation.play_weather_greeting_ifttt
      - automation.rain_clothes_drying_outside
      - automation.rain_reset_clothes_drying_outside_input_boolean
      - automation.rain_skylights_left_open
      - automation.scene_guests_mode_off
      - automation.scene_guests_mode_on
      - automation.scene_holidays
      - automation.scene_movies
      - automation.scene_normal
      - automation.scene_normal_from_movies
      - automation.scene_xmas_off
      - automation.scene_xmas_on
      - automation.set_ga_volume_to_high_daytime
      - automation.set_ga_volume_to_low_at_night
      - automation.set_kello_volume
      - automation.set_onkyo_to_streambox_when_kodi_or_mibox_cc_is_playing
      - automation.ssl_expiry_notification
      - automation.staircase_led_strip_off_by_pir
      - automation.staircase_led_strip_on_by_pir
      - automation.staircase_light_off_by_pir
      - automation.staircase_light_on_by_pir
      - automation.start_dehumidifier
      - automation.stop_dehumidifier
      - automation.stop_radio_on_kello
      - automation.switch_everything_off_when_we_leave_home
      - automation.tell_div_lolo_left_work
      - automation.tell_div_lolo_reached_work
      - automation.tell_lolo_div_left_work
      - automation.tell_lolo_div_left_yoga
      - automation.tell_lolo_of_a_long_drive_home
      - automation.turn_alert_off
      - automation.turn_baubles_on_1
      - automation.turn_baubles_on_2
      - automation.turn_baubles_on_3
      - automation.turn_movies_on_when_kodi_is_playing
      - automation.turn_movies_on_when_netflix_or_prime_is_playing
      - automation.turn_multimedia_off_if_all_multimedia_is_off
      - automation.turn_multimedia_off_if_multimedia_switch_goes_off
      - automation.turn_multimedia_switch_on_if_sky_tv_or_onkyo_is_on
      - automation.turn_onkyo_off_when_stop_playing_on_chromecast
      - automation.turn_onkyo_on_when_tv_goes_on
      - automation.tv_cabinet_led_strip_off_by_pir
      - automation.tv_cabinet_led_strip_on_pir
      - automation.unmute_kello_alarms
      - automation.vacuum_error_continue
      - automation.vacuum_error_stop
      - automation.vacuum_finished_vacuuming
      - automation.vacuum_scheduled_vacuuming
      - automation.vacuum_start_vacuuming
      - automation.vacuum_started_vacuuming
      - automation.window_door_or_window_opens_closes
      - automation.window_downstairs_window_left_open_at_night
      - automation.xiaomi_switch_automatic_battery_charging
      - automation.xiaomi_switch_battery_is_charged_turning_xiaomi_switch_off
      - automation.xiaomi_switch_charge_if_no_rain
      - automation.xiaomi_switch_start_charging_battery
      - automation.xmas_lights_off
      - automation.xmas_lights_on
      - automation.zigbee_network_map_update
