title: Automation
background: url("/local/calendar-check.png") fixed
icon: mdi:calendar-check
cards:
  - type: custom:auto-entities
    card:
      type: custom:fold-entity-row
      head:
        type: section
        label: All Automations
      open: true
    filter:
      include:
        - entity_id: "automation.*"