- alias: Turn Onkyo On When TV Goes On
  trigger:
  - platform: state
    entity_id: media_player.panasonic_viera_tv
    to: 'on'
  action:
  - service: media_player.turn_on
    entity_id: media_player.onkyo_txnr656