- alias: Movies
  trigger:
    - platform: state
      entity_id: input_boolean.movies
      to: 'on'
  action:
    - service: tts.google_say
      entity_id: media_player.mpd
      data:
        message: 'Scene, movies, activated'
    - service: scene.turn_on
      entity_id: scene.movies

    - service: input_boolean.turn_off
      entity_id: input_boolean.normal
    - service: input_boolean.turn_off
      entity_id: input_boolean.holidays
    - service: light.turn_on
      data:
        entity_id: light.living_room_wall
        brightness: 255
    - service: light.turn_off
      data:
        entity_id: light.living_room_main
    - service: input_slider.select_value
      data_template: 
        entity_id:
          - input_slider.tv_cabinet_r
        value: 255
    - service: input_slider.select_value
      data_template: 
        entity_id:
          - input_slider.tv_cabinet_g
        value: 0
    - service: input_slider.select_value
      data_template: 
        entity_id:
          - input_slider.tv_cabinet_b
        value: 0
    - service: shell_command.tv_cabinet_on
      data_template:
        R: '{{ states.input_slider.tv_cabinet_r.state | round(0) }}'
        G: '{{ states.input_slider.tv_cabinet_g.state | round(0) }}'
        B: '{{ states.input_slider.tv_cabinet_b.state | round(0) }}'
