- alias: Xmas
  trigger:
    - platform: state
      entity_id: input_boolean.xmas
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.xmas
    - service: tts.google_say
      entity_id: media_player.living_room_google_mini
      data:
        message: 'Scene, christmas, activated'
    - service: group.set_visibility
      entity_id: group.baubles
      data:
        visible: True

- alias: Xmas Off
  trigger:
    - platform: state
      entity_id: input_boolean.xmas
      to: 'off'
  action:
    - service: tts.google_say
      entity_id: media_player.living_room_google_mini
      data:
        message: 'Scene, christmas, de-activated'
    - service: group.set_visibility
      entity_id: group.baubles
      data:
        visible: False
