- platform: mqtt_json
  name: House Number LED Strip
  state_topic: "led_strip/housenumber"
  command_topic: "led_strip/housenumber/set"
  brightness: true
  rgb: true
  effect: true
  effect_list: [colorfade_slow, colorfade_fast, flash]
  optimistic: false
  qos: 0

- platform: mqtt_json
  name: Staircase LED Strip
  state_topic: "led_strip/staircase"
  command_topic: "led_strip/staircase/set"
  brightness: true
  rgb: true
  effect: true
  effect_list: [colorfade_slow, colorfade_fast, flash]
  optimistic: false
  qos: 0

- platform: mqtt_json
  name: TV Cabinet LED Strip
  state_topic: "led_strip/tvcabinet"
  command_topic: "led_strip/tvcabinet/set"
  brightness: true
  rgb: true
  effect: true
  effect_list: [colorfade_slow, colorfade_fast, flash]
  optimistic: false
  qos: 0




- platform: mqtt_json
  name: Bauble 1
  state_topic: "WeMosBauble/Bauble1"
  command_topic: "WeMosBauble/Bauble1/set"
  brightness: false
  rgb: false
  effect: true
  effect_list: [sparkle, rainbow, uniglow]
  optimistic: false
  qos: 0

- platform: mqtt_json
  name: Bauble 2
  state_topic: "WeMosBauble/Bauble2"
  command_topic: "WeMosBauble/Bauble2/set"
  brightness: false
  rgb: false
  effect: true
  effect_list: [sparkle, rainbow, uniglow]
  optimistic: false
  qos: 0

- platform: mqtt_json
  name: Bauble 3
  state_topic: "WeMosBauble/Bauble3"
  command_topic: "WeMosBauble/Bauble3/set"
  brightness: false
  rgb: false
  effect: true
  effect_list: [sparkle, rainbow, uniglow]
  optimistic: false
  qos: 0




- platform: mqtt_json
  name: "Conservatory LED Strip"
  state_topic: "Conservatory/LED_Strip"
  command_topic: "Conservatory/LED_Strip/set"
  effect: true
  effect_list:
    - bpm
    - candy cane  
    - confetti  
    - cyclon rainbow  
    - dots  
    - fire  
    - glitter  
    - juggle  
    - lightning
    - noise  
    - police all  
    - police one  
    - rainbow  
    - rainbow with glitter  
    - ripple  
    - sinelon  
    - solid  
    - twinkle  
  brightness: true
  flash: true
  rgb: true
  optimistic: false
  qos: 0


- platform: mqtt_json
  name: "Garage LED Strip"
  state_topic: "Garage/LED_Strip"
  command_topic: "Garage/LED_Strip/set"
  effect: true
  effect_list:
    - bpm
    - candy cane  
    - confetti  
    - cyclon rainbow  
    - dots  
    - fire  
    - glitter  
    - juggle  
    - lightning
    - noise  
    - police all  
    - police one  
    - rainbow  
    - rainbow with glitter  
    - ripple  
    - sinelon  
    - solid  
    - twinkle  
  brightness: true
  flash: true
  rgb: true
  optimistic: false
  qos: 0
