- platform: template
  sensors:
    edimax1_watts:
      entity_id: switch.edimax1
      value_template: '{{state_attr("switch.edimax1","current_power_w")|float}}'
      unit_of_measurement: 'W'
      friendly_name: Edimax1 Watts