- platform: template
  sensors:
    edimax1_watts:
      value_template: '{{ states.switch.edimax1.attributes["current_power_w"] | float * 1000000 | round(2) }}'
      unit_of_measurement: 'W'
      friendly_name: Edimax1 Watts