- platform: mqtt
  name: "RTL2_Pic"
  state_topic: "RadioStream/RTL2/pic_url"
  value_template: "{{ value }}"

- platform: mqtt
  name: "RTL2_Artist"
  state_topic: "RadioStream/RTL2/artist"
  value_template: "{{ value }}"

- platform: mqtt
  name: "RTL2_Track"
  state_topic: "RadioStream/RTL2/track"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Absolute_Radio_Pic"
  state_topic: "RadioStream/Absolute_Radio/pic_url"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Absolute_Radio_Artist"
  state_topic: "RadioStream/Absolute_Radio/artist"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Absolute_Radio_Track"
  state_topic: "RadioStream/Absolute_Radio/track"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Absolute_Radio_CR_Pic"
  state_topic: "RadioStream/Absolute_Radio_CR/pic_url"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Absolute_Radio_CR_Artist"
  state_topic: "RadioStream/Absolute_Radio_CR/artist"
  value_template: "{{ value }}"

- platform: mqtt
  name: "ha_podcast"
  state_topic: "RadioStream/Hass Podcast/mp3_url"
  value_template: "{{ value }}"

- platform: mqtt
  name: "ha_podcast_track"
  state_topic: "RadioStream/Hass Podcast/track"
  value_template: "{{ value }}"

- platform: mqtt
  name: "Absolute_Radio_CR_Track"
  state_topic: "RadioStream/Absolute_Radio_CR/track"
  value_template: "{{ value }}"

- platform: mqtt
  name: "internet_of_things_podcast"
  state_topic: "RadioStream/IoT Podcast/mp3_url"
  value_template: "{{ value }}"

- platform: mqtt
  name: "internet_of_things_podcast_track"
  state_topic: "RadioStream/IoT Podcast/track"
  value_template: "{{ value }}"

# - platform: scrape
  # resource: https://www.6play.fr/rtl2/quel-est-ce-titre
  # name: RTL2_Pic
  # select: '.ecfper-2'
  # attribute: src

# - platform: scrape
  # resource: https://www.6play.fr/rtl2/quel-est-ce-titre
  # name: RTL2_Artist
  # select: '.ecfper-6'
  # value_template: '{{ value | title }}'

# - platform: scrape
  # resource: https://www.6play.fr/rtl2/quel-est-ce-titre
  # name: RTL2_Track
  # select: '.ecfper-5'
  # value_template: '{{ value | title }}'

# - platform: scrape
  # resource: https://absoluteradio.co.uk/classic-rock/music/
  # name: Absolute_Radio_CR_Pic
  # select: '.song-artist-image img'
  # attribute: src

# - platform: scrape
  # resource: https://absoluteradio.co.uk/classic-rock/music/
  # name: Absolute_Radio_CR_Artist
  # select: '.song-artist-image img'
  # attribute: alt

# - platform: scrape
  # resource: https://absoluteradio.co.uk/classic-rock/music/
  # name: Absolute_Radio_CR_Track
  # select: '.song-title a'

# - platform: scrape
  # resource: https://absoluteradio.co.uk/absolute-radio/music/
  # name: Absolute_Radio_Pic
  # select: '.song-artist-image img'
  # attribute: src

# - platform: scrape
  # resource: https://absoluteradio.co.uk/absolute-radio/music/
  # name: Absolute_Radio_Artist
  # select: '.song-artist-image img'
  # attribute: alt

# - platform: scrape
  # resource: https://absoluteradio.co.uk/absolute-radio/music/
  # name: Absolute_Radio_Track
  # select: '.song-title a'

# - platform: scrape
  # resource: https://hasspodcast.io/feed/podcast
  # name: ha_podcast
  # select: 'enclosure:nth-of-type(1)'
  # attribute: url

# - platform: scrape
  # resource: https://hasspodcast.io/feed/podcast
  # name: ha_podcast_track
  # select: 'item:nth-of-type(1) title'

# - platform: scrape
  # resource: https://iotpodcast.com/feed/
  # name: internet_of_things_podcast
  # select: 'enclosure:nth-of-type(1)'
  # attribute: url

# - platform: scrape
  # resource: https://iotpodcast.com/feed/
  # name: internet_of_things_podcast_track
  # select: 'item:nth-of-type(1) title'


- platform: template
  sensors:
    stream_artist:
      entity_id:
        - sensor.rtl2_artist
        - sensor.absolute_radio_cr_artist
        - sensor.absolute_radio_artist
        - sensor.rtl2_track
        - sensor.absolute_radio_track
        - sensor.absolute_radio_cr_track
        - sensor.ha_podcast_track
        - sensor.rtl2_pic
        - sensor.absolute_radio_cr_pic
        - sensor.absolute_radio_pic
        - input_select.chromecast_radio_station
        - input_select.chromecast_radio_speakers
      value_template: >
        {% if is_state("input_select.chromecast_radio_station", "RTL2") %} {{states("sensor.rtl2_artist")}}
        {% elif is_state("input_select.chromecast_radio_station", "Absolute Radio") %} {{states("sensor.absolute_radio_artist")}}
        {% elif is_state("input_select.chromecast_radio_station", "Absolute Radio Classic Rock") %} {{states("sensor.absolute_radio_CR_artist")}}
        {% elif is_state("input_select.chromecast_radio_station", "Hit West") %} N/A
        {% elif is_state("input_select.chromecast_radio_station", "HA Podcast") %} Phil & Rohan
        {% elif is_state("input_select.chromecast_radio_station", "IoT Podcast") %} Stacey & Kevin
        {% elif is_state("input_select.chromecast_radio_station", "Chill") %} N/A
        {% elif is_state("input_select.chromecast_radio_station", "Radio Fiji Two") %} N/A
        {% elif is_state("input_select.chromecast_radio_station", "Custom Station") %} N/A
        {% endif %}
      friendly_name: Artist
      icon_template: 'mdi:account'
    stream_track:
      entity_id:
        - sensor.rtl2_artist
        - sensor.absolute_radio_cr_artist
        - sensor.absolute_radio_artist
        - sensor.rtl2_track
        - sensor.absolute_radio_track
        - sensor.absolute_radio_cr_track
        - sensor.ha_podcast_track
        - sensor.rtl2_pic
        - sensor.absolute_radio_cr_pic
        - sensor.absolute_radio_pic
        - sensor.internet_of_things_podcast_track
        - input_select.chromecast_radio_station
        - input_select.chromecast_radio_speakers
      value_template: >
        {% if is_state("input_select.chromecast_radio_station", "RTL2") %} {{states("sensor.rtl2_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Absolute Radio") %} {{states("sensor.absolute_radio_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Absolute Radio Classic Rock") %} {{states("sensor.absolute_radio_CR_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Hit West") %} N/A
        {% elif is_state("input_select.chromecast_radio_station", "HA Podcast") %} {{states("sensor.ha_podcast_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "IoT Podcast") %} {{states("sensor.internet_of_things_podcast_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Chill") %} N/A
        {% elif is_state("input_select.chromecast_radio_station", "Radio Fiji Two") %} N/A
        {% elif is_state("input_select.chromecast_radio_station", "Custom Station") %} N/A
        {% endif %}
      friendly_name: Artist
      icon_template: 'mdi:account'
