- platform: scrape
  resource: https://www.rtl2.fr/direct
  name: RTL2_Pic
  select: 'img[class="pic img-echo timeline-media--music__img"]'
  attribute: data-src

- platform: scrape
  resource: https://www.rtl2.fr/direct
  name: RTL2_Artist
  select: 'span[class="timeline-media--music__artist"]'
  value_template: '{{ value | title }}'

- platform: scrape
  resource: https://www.rtl2.fr/direct
  name: RTL2_Track
  select: 'strong[class="timeline-media--music__title"]'
  value_template: '{{ value | title }}'

- platform: scrape
  resource: https://absoluteradio.co.uk/classic-rock/music/
  name: Absolute_Radio_CR_Pic
  select: '.song-artist-image img'
  attribute: src

- platform: scrape
  resource: https://absoluteradio.co.uk/classic-rock/music/
  name: Absolute_Radio_CR_Artist
  select: '.song-artist-image img'
  attribute: alt

- platform: scrape
  resource: https://absoluteradio.co.uk/classic-rock/music/
  name: Absolute_Radio_CR_Track
  select: '.song-title a'

- platform: scrape
  resource: https://absoluteradio.co.uk/absolute-radio/music/
  name: Absolute_Radio_Pic
  select: '.song-artist-image img'
  attribute: src

- platform: scrape
  resource: https://absoluteradio.co.uk/absolute-radio/music/
  name: Absolute_Radio_Artist
  select: '.song-artist-image img'
  attribute: alt

- platform: scrape
  resource: https://absoluteradio.co.uk/absolute-radio/music/
  name: Absolute_Radio_Track
  select: '.song-title a'

- platform: scrape
  resource: https://hasspodcast.io/feed/podcast
  name: ha_podcast
  select: 'enclosure:nth-of-type(1)'
  attribute: url

- platform: scrape
  resource: https://hasspodcast.io/feed/podcast
  name: ha_podcast_track
  select: 'item:nth-of-type(1) title'

- platform: scrape
  resource: https://iotpodcast.com/feed/
  name: internet_of_things_podcast
  select: 'enclosure:nth-of-type(1)'
  attribute: url

- platform: scrape
  resource: https://iotpodcast.com/feed/
  name: internet_of_things_podcast_track
  select: 'item:nth-of-type(1) title'


- platform: template
  sensors:
    stream_artist:
      entity_id:
        - sensor.rtl2_artist
        - sensor.absolute_radio_cr_artist
        - sensor.absolute_radio_artist
        - sensor.rtl2_track
        - sensor.absolute_radio_track
        - sensor.absolute_radio_cr_track
        - sensor.ha_podcast_track
        - sensor.rtl2_pic
        - sensor.absolute_radio_cr_pic
        - sensor.absolute_radio_pic
        - input_select.chromecast_radio_station
        - input_select.chromecast_radio_speakers
      value_template: >
        {% if is_state("input_select.chromecast_radio_station", "RTL2") %} {{states("sensor.rtl2_artist")}}
        {% elif is_state("input_select.chromecast_radio_station", "Absolute Radio") %} {{states("sensor.absolute_radio_artist")}}
        {% elif is_state("input_select.chromecast_radio_station", "Absolute Radio Classic Rock") %} {{states("sensor.absolute_radio_CR_artist")}}
        {% elif is_state("input_select.chromecast_radio_station", "Hit West") %} N/A
        {% elif is_state("input_select.chromecast_radio_station", "HA Podcast") %} Phil & Rohan
        {% elif is_state("input_select.chromecast_radio_station", "IoT Podcast") %} Stacey & Kevin
        {% elif is_state("input_select.chromecast_radio_station", "Chill") %} N/A
        {% elif is_state("input_select.chromecast_radio_station", "Radio Fiji Two") %} N/A
        {% elif is_state("input_select.chromecast_radio_station", "Custom Station") %} N/A
        {% endif %}
      friendly_name: Artist
      icon_template: 'mdi:account'
    stream_track:
      entity_id:
        - sensor.rtl2_artist
        - sensor.absolute_radio_cr_artist
        - sensor.absolute_radio_artist
        - sensor.rtl2_track
        - sensor.absolute_radio_track
        - sensor.absolute_radio_cr_track
        - sensor.ha_podcast_track
        - sensor.rtl2_pic
        - sensor.absolute_radio_cr_pic
        - sensor.absolute_radio_pic
        - sensor.internet_of_things_podcast_track
        - input_select.chromecast_radio_station
        - input_select.chromecast_radio_speakers
      value_template: >
        {% if is_state("input_select.chromecast_radio_station", "RTL2") %} {{states("sensor.rtl2_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Absolute Radio") %} {{states("sensor.absolute_radio_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Absolute Radio Classic Rock") %} {{states("sensor.absolute_radio_CR_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Hit West") %} N/A
        {% elif is_state("input_select.chromecast_radio_station", "HA Podcast") %} {{states("sensor.ha_podcast_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "IoT Podcast") %} {{states("sensor.internet_of_things_podcast_track")}}
        {% elif is_state("input_select.chromecast_radio_station", "Chill") %} N/A
        {% elif is_state("input_select.chromecast_radio_station", "Radio Fiji Two") %} N/A
        {% elif is_state("input_select.chromecast_radio_station", "Custom Station") %} N/A
        {% endif %}
      friendly_name: Artist
      icon_template: 'mdi:account'
    radio_is_streaming:
      entity_id:
        - media_player.conservatory
        - media_player.house
        - media_player.kitchen
        - media_player.onkyo
        - media_player.onkyo_tx_nr656
      value_template: >
        {% for state in states.media_player -%}
        {%- if state.entity_id in ["media_player.conservatory", "media_player.house", "media_player.kitchen",  "media_player.onkyo", "media_player.onkyo_tx_nr656"] -%}
        {% if state_attr(state.entity_id, "media_content_id") in ["http://streaming.radio.rtl2.fr:80/rtl2-1-44-96", "http://icy-e-bab-04-cr.sharp-stream.com/absoluteradio.mp3", "http://icy-e-bab-04-cr.sharp-stream.com/absoluteclassicrock.mp3", "http://broadcast.infomaniak.ch/hitwest-high.mp3", states("sensor.ha_podcast"), states("sensor.internet_of_things_podcast"), "http://media-the.musicradio.com/ChillMP3", "http://peridot.streamguys.com:7150/RFTwo?play", states("input_text.custom_station")] %}yes{% endif %}
        {% endif %}  
        {%- endfor %}
