- platform: rfxtrx
  automatic_add: True
  devices:
    0A520700240E00E4360179:
      name: Upstairs
      data_type:
       - Humidity
       - Temperature
    0A520700420E0104260269:
      name: Loft
      data_type:
       - Humidity
       - Temperature
    0716004500910560:
      name: doorbell
      data_type:
       - Sound
      fire_event: true


# - platform: command_line
  # name: Doorbell Last Rang
  # command: "/home/cctv/.homeassistant/shell_scripts/doorbell_last_fired.py"


- platform: mqtt
  state_topic: "Sensors/DoorBellLastFired"
  name: "Doorbell Last Rang"