- platform: scrape
  resource: https://www.rtl2.fr/direct
  name: RTL2_Pic
  select: 'img[class="pic img-echo timeline-media--music__img"]'
  attribute: data-src

- platform: scrape
  resource: https://www.rtl2.fr/direct
  name: RTL2_Artist
  select: 'span[class="timeline-media--music__artist"]'
  value_template: '{{ value | title }}'

- platform: scrape
  resource: https://www.rtl2.fr/direct
  name: RTL2_Track
  select: 'strong[class="timeline-media--music__title"]'
  value_template: '{{ value | title }}'

- platform: template
  sensors:
    current_speaker:
      value_template: >
        {% if is_state("input_select.chromecast_radio", "Kitchen") %} Kitchen
        {% elif is_state("input_select.chromecast_radio", "Onkyo") %} Onkyo
        {% elif is_state("input_select.chromecast_radio", "Conservatory") %} Conservatory
        {% elif is_state("input_select.chromecast_radio", "House") %} House
        {% endif %}
      friendly_name: Speaker
      icon_template: 'mdi:speaker'
