- platform: rest
  resource: http://192.168.0.23:8080/3/detection/status
  name: dafang_living_room_status_scrape
  value_template: '{{ value.split("Detection status ")[1] }}'

- platform: rest
  resource: http://192.168.0.23:8080/4/detection/status
  name: dafang_kitchen_status_scrape
  value_template: '{{ value.split("Detection status ")[1] }}'

- platform: rest
  resource: http://192.168.0.23:8080/2/detection/status
  name: cctv_garage_status_scrape
  value_template: '{{ value.split("Detection status ")[1] }}'

- platform: rest
  resource: http://192.168.0.23:8080/3/detection/connection
  name: dafang_living_room_connection_scrape
  value_template: '{{ value.split("Camera 3 Connection ")[1] }}'

- platform: rest
  resource: http://192.168.0.23:8080/4/detection/connection
  name: dafang_kitchen_connection_scrape
  value_template: '{{ value.split("Camera 4 Connection ")[1] }}'

- platform: rest
  resource: http://192.168.0.23:8080/2/detection/connection
  name: cctv_garage_connection_scrape
  value_template: '{{ value.split("Camera 2 Connection ")[1] }}'

- platform: scrape
  resource: https://www.home-assistant.io
  name: ha_online_version
  select: ".current-version h1"
  value_template: '{{ value.split(":")[1] }}'