- platform: waze_travel_time
  name: Home to Work
  origin: !secret postcode_home
  destination: !secret postcode_work
  region: 'EU'

- platform: waze_travel_time
  name: Lolo to Home
  origin: device_tracker.lolo
  destination: !secret postcode_home
  region: 'EU'



- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - icon
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_high
    - temperature_low
    - temperature
    - humidity
    - precip_intensity_max

- platform: wunderground
  api_key: !secret wu_api_key
  monitored_conditions:
    - precip_today_metric
    - precip_1d_mm 
    - precip_1d 
    - wind_dir
    - wind_1d_kph 
    - wind_gust_1d_kph 

- platform: template
  sensors:
    sunset_time:
      value_template: >
        {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%H:%M") }}
      friendly_name: Sunset
      icon_template: '{% if states.sun.sun.state == "above_horizon" %}mdi:white-balance-sunny{% else %}mdi:weather-night{% endif %}'

- platform: template
  sensors:
    precipitation:
      value_template: >
        {{(states.sensor.dark_sky_daily_max_precip_intensity.state | float * 10) | round(1)}}
      friendly_name: Precipitation
      unit_of_measurement: "mm"


- platform: version

- platform: random
  name: bauble_random_effect
  minimum: 1
  maximum: 3
  scan_interval: 290