- platform: waze_travel_time
  name: Home to Work
  origin: !secret postcode_home
  destination: !secret postcode_work
  region: 'EU'

- platform: waze_travel_time
  name: Lolo to Home
  origin: device_tracker.lolo
  destination: !secret postcode_home
  region: 'EU'



- platform: darksky
  api_key: !secret darksky_api_key
  forecast:
    - 0
  monitored_conditions:
    - summary
    - icon
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature
    - humidity
    - temperature_high
    - temperature_low
    - precip_intensity_max
    - wind_speed
    - wind_gust

- platform: wunderground
  api_key: !secret wu_api_key
  monitored_conditions:
    - precip_today_metric
    - precip_1d_mm 
    - precip_1d 
    - wind_dir
    - wind_1d_kph 
    - wind_gust_1d_kph 

- platform: template
  sensors:
    sunset_time:
      entity_id: sun.sun
      value_template: >
        {{ as_timestamp(state_attr("sun.sun","next_setting")) | timestamp_custom("%H:%M") }}
      friendly_name: Sunset
      icon_template: '{% if states("sun.sun") == "above_horizon" %}mdi:white-balance-sunny{% else %}mdi:weather-night{% endif %}'

- platform: template
  sensors:
    precipitation:
      entity_id: sensor.dark_sky_daily_max_precip_intensity_0
      value_template: >
        {{(states("sensor.dark_sky_daily_max_precip_intensity_0") | float * 10) | round(1)}}
      friendly_name: Precipitation
      unit_of_measurement: "mm"


- platform: version
- platform: uptime
  unit_of_measurement: hours

- platform: random
  name: bauble_random_effect
  minimum: 1
  maximum: 3
  scan_interval: 290
  
  
- platform: seventeentrack
  username: !secret seventeentrack_email
  password: !secret seventeentrack_passwqord
  show_delivered: true