- platform: google_travel_time
  name: Home to Verint
  api_key: !secret google_travel_api_key
  origin: RH10 7YS
  destination: KT13 0RH
  options:
    units: imperial

- platform: google_travel_time
  name: Lolo to Home
  api_key: !secret google_travel_api_key
  origin: device_tracker.zevsmpjl_lolo_iphone
  destination: RH10 7YS
  options:
    units: imperial

- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - icon
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_max
    - temperature_min
    - temperature
    - precip_intensity_max

- platform: wunderground
  api_key: !secret wu_api_key
  monitored_conditions:
    - precip_today_metric
    - precip_1d_mm 
    - precip_1d 
    - wind_dir
    - wind_1d_kph 
    - wind_gust_1d_kph 

- platform: template
  sensors:
    sunset_time:
      value_template: >
        {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%H:%M") }}
      friendly_name: Sunset

- platform: template
  sensors:
    precipitation:
      value_template: >
        {{(states.sensor.dark_sky_daily_max_precip_intensity.state | float * 10) | round(1)}}
      friendly_name: Precipitation
      unit_of_measurement: "mm"


- platform: version

# - platform: mold_indicator
  # indoor_temp_sensor: sensor.upstairs_temperature
  # indoor_humidity_sensor: sensor.upstairs_humidity
  # outdoor_temp_sensor: sensor.outside_temperature
  # calibration_factor: 2.0
- platform: random
  name: bauble_random_effect
  minimum: 1
  maximum: 3
  scan_interval: 290