- platform: command_line
  name: sky_hd_status2
  command: curl -i -s -o /dev/null -w "%{http_code}" 'http://192.168.0.7:49159/photo-viewing/start?uri=http://192.168.0.24/null.jpg'
  scan_interval: 15