- platform: template
  sensors:
    xiaomi_battery_level:
      entity_id:
        - vacuum.mi_robot_vacuum
      value_template: >
        {{ states.vacuum.mi_robot_vacuum.attributes.battery_level }}
      friendly_name: Battery Level
      unit_of_measurement: '%'


    xiaomi_cleaned_area:
      entity_id:
        - vacuum.mi_robot_vacuum
      value_template: >
        {{ states.vacuum.mi_robot_vacuum.attributes.cleaned_area }}
      friendly_name: Cleaned Area
      unit_of_measurement: 'm²'


    xiaomi_status:
      entity_id:
        - vacuum.mi_robot_vacuum
      value_template: >
        {{ states.vacuum.mi_robot_vacuum.attributes.status }}
      friendly_name: Status


    xiaomi_cleaning_time:
      entity_id:
        - vacuum.mi_robot_vacuum
      value_template: >
        {{ states.vacuum.mi_robot_vacuum.attributes.cleaning_time }}
      friendly_name: Cleaning Time
      unit_of_measurement: 'min'



- platform: command_line
  name: Last Clean
  command: "/home/cctv/.homeassistant/shell_scripts/xiaomi_last_clean.py"



- platform: miflora
  mac: 'C4:7C:8D:65:C6:B9'
  name: Basil
  monitored_conditions:
    - temperature
    - moisture
    - light
    - conductivity
    - battery