- platform: template
  sensors:
    xiaomi_battery_level:
      value_template: >
        {{ states.vacuum.mi_robot_vacuum.attributes.battery_level }}
      friendly_name: Battery Level
      unit_of_measurement: '%'


    xiaomi_cleaned_area:
      value_template: >
        {{ states.vacuum.mi_robot_vacuum.attributes.cleaned_area }}
      friendly_name: Cleaned Area
      unit_of_measurement: 'm²'


    xiaomi_status:
      value_template: >
        {{ states.vacuum.mi_robot_vacuum.state }}
      friendly_name: Status


    xiaomi_cleaning_time:
      value_template: >
        {{ states.vacuum.mi_robot_vacuum.attributes.cleaning_time }}
      friendly_name: Cleaning Time
      unit_of_measurement: 'min'


    xiaomi_main_brush_left:
      value_template: >
        {{ states.vacuum.mi_robot_vacuum.attributes.main_brush_left }}
      friendly_name: Main Brush Left
      unit_of_measurement: 'Hrs'


    xiaomi_side_brush_left:
      value_template: >
        {{ states.vacuum.mi_robot_vacuum.attributes.side_brush_left }}
      friendly_name: Side Brush Left
      unit_of_measurement: 'Hrs'


    xiaomi_filter_left:
      value_template: >
        {{ states.vacuum.mi_robot_vacuum.attributes.filter_left }}
      friendly_name: Filter Left
      unit_of_measurement: 'Hrs'


    xiaomi_sensor_dirty_left:
      value_template: >
        {{ states.vacuum.mi_robot_vacuum.attributes.sensor_dirty_left }}
      friendly_name: Filter Left
      unit_of_measurement: 'Hrs'



# - platform: command_line
  # name: Last Clean
  # command: "/home/cctv/.homeassistant/shell_scripts/xiaomi_last_clean.py"


- platform: mqtt
  state_topic: "Sensors/XiaomiLastClean"
  name: "Last Clean"


- platform: miflora
  mac: 'C4:7C:8D:65:C6:B9'
  name: Aloe Vera
  monitored_conditions:
    - temperature
    - moisture
    - light
    - conductivity
    - battery
  median: 3