- platform: template
  sensors:
    outside_temp_sensor_lost:
      entity_id:
        - sensor.outside_temperature
      value_template: >
        {{(as_timestamp(now()) - as_timestamp(states.sensor.outside_temperature.last_updated) | int > 3600 )}}
      friendly_name: Outside Temp Sensor Lost

    upstairs_temp_sensor_lost:
      entity_id:
        - sensor.upstairs_temperature
      value_template: >
        {{(as_timestamp(now()) - as_timestamp(states.sensor.upstairs_temperature.last_updated) | int > 3600 )}}
      friendly_name: Upstairs Temp Sensor Lost