- platform: template
  sensors:
    basil_humidity_too_low:
      value_template: >
        {{ (((states.sensor.basil_moisture.state )| default(100)) | int < 15) and (as_timestamp(now()) - as_timestamp(states.automation.hass_start_sound.attributes.last_triggered | default(0)) | int > 900)}}
      friendly_name: Basil Humidity below 15%

    basil_battery_too_low:
      value_template: >
        {{ (((states.sensor.basil_battery.state) | default(100)) | int < 10) and (as_timestamp(now()) - as_timestamp(states.automation.hass_start_sound.attributes.last_triggered | default(0)) | int > 900)}}
      friendly_name: Basil Battery below 10%



    outside_temp_sensor_lost:
      value_template: >
        {{(as_timestamp(now()) - as_timestamp(states.sensor.outside_temperature.last_updated | default(0)) | int > 3600 )}}
      friendly_name: Outside Temp Sensor Lost

    upstairs_temp_sensor_lost:
      value_template: >
        {{(as_timestamp(now()) - as_timestamp(states.sensor.upstairs_temperature.last_updated | default(0)) | int > 3600 )}}
      friendly_name: Upstairs Temp Sensor Lost

    currentcost_lost:
      value_template: >
        {% if (as_timestamp(now()) - (as_timestamp(states.sensor.currentcost_power.last_updated) | int)) < 300 %}off{% else %}on{% endif %}
      friendly_name: CurrentCost Lost

    ram_too_high:
      value_template: >
        {{ states.sensor.ram_usage.state | default(0) | int > 90 }}
      friendly_name: RAM Too High

    home_disk_usage_too_high:
      value_template: >
        {{ states.sensor.home_disk_usage.state | default(0) | int > 90 }}
      friendly_name: Home Disk Usage Too High

    root_disk_usage_too_high:
      value_template: >
        {{ states.sensor.root_disk_usage.state | default(0) | int > 90 }}
      friendly_name: Root Disk Usage Too High

