- platform: bayesian
  name: 'Dark'
  prior: 0.1
  probability_threshold: 0.9
  device_class: light
  observations:
    - platform: state
      entity_id: sun.sun
      prob_given_true: 0.9
      prob_given_false: 0.1
      to_state: 'below_horizon'
    - platform: template
      prob_given_true: 0.9
      prob_given_false: 0.1
      value_template: >
        {{is_state('binary_sensor.photoresistor','off') and is_state('light.living_room_main','off')}}

    - platform: template
      prob_given_true: 0.7
      prob_given_false: 0.1
      value_template: >
        {{(states('sensor.dafang_kitchen_brightness_mean') | int < 63) and is_state('group.kitchen_lights','off')}}
    - platform: template
      prob_given_true: 0.7
      prob_given_false: 0.1
      value_template: >
        {{(states('sensor.dafang_living_room_brightness_mean') | int < 63) and is_state('light.living_room_main','off')}}

    # - platform: 'state'
      # entity_id: 'group.kitchen_lights'
      # prob_given_true: 0.9
      # prob_given_false: 0.1
      # to_state: 'on'
    # - platform: 'state'
      # entity_id: 'light.living_room_main'
      # prob_given_true: 0.9
      # prob_given_false: 0.1
      # to_state: 'on'
    # - platform: 'state'
      # entity_id: 'light.conservatory'
      # prob_given_true: 0.9
      # prob_given_false: 0.1
      # to_state: 'on'

  # - platform: bayesian
    # prior: 0.1
    # observations:
      # - entity_id: 'switch.kitchen_lights'
        # prob_given_true: 0.6
        # prob_given_false: 0.2
        # platform: 'state'
        # to_state: 'on'