- platform: command_line
  command: "/home/cctv/.homeassistant/shell_scripts/CCTV_Checker.py 1"
  name: cctv_front_status

- platform: command_line
  command: "/home/cctv/.homeassistant/shell_scripts/CCTV_Checker.py 2"
  name: cctv_garage_status