- platform: template
  sensors:
    cctv_front:
      entity_id:
        - sensor.cctv_front_status
      value_template: >
        {{ states.sensor.cctv_front_status.state == 'Connection OK'}}
      friendly_name: CCTV Front
      device_class: connectivity

    cctv_garage:
      entity_id:
        - sensor.cctv_garage_status
      value_template: >
        {{ states.sensor.cctv_garage_status.state == 'Connection OK'}}
      friendly_name: CCTV Garage
      device_class: connectivity