- platform: template
  sensors:
    dafang_living_room_status:
      entity_id: input_boolean.pir_living_room_back
      value_template: >
        {{ states("input_boolean.pir_living_room_back") == 'ACTIVE'}}
      friendly_name: Dafang Living Room motion Status
      device_class: power


