- platform: ping
  host: 192.168.0.22
  name: RPi

- platform: ping
  host: 192.168.0.3
  name: MAIN

- platform: ping
  host: 192.168.0.40
  name: TV Cabinet LED Strip

- platform: ping
  host: 192.168.0.41
  name: StairCase LED Strip

- platform: ping
  host: 192.168.0.42
  name: House Number LED Strip

- platform: ping
  host: 192.168.0.17
  name: Kello

- platform: ping
  host: 192.168.0.21
  name: RPi Zero W

- platform: ping
  host: 192.168.0.30
  name: Verint CCTV

- platform: ping
  host: 192.168.0.31
  name: Hikvision CCTV

- platform: ping
  host: 192.168.0.32
  name: Xiaomi Dafang CCTV