- platform: rfxtrx
  automatic_add: True
  devices:
    0B11002B00018F3C0A010F60:
      name: Garage Back Door
      device_class: door
    0B1100300001B0240A000050:
      name: Conservatory Skylight Left
      device_class: opening