- platform: rest
  resource: http://192.168.0.22:3000/digital/18
  name: PIR Kitchen aRest
  value_template: "{%if value_json.return_value == 1 %}on{%elif value_json.return_value == 0 %}off{% endif %}"
  device_class: motion

- platform: rest
  resource: http://192.168.0.22:3000/digital/7
  name: Door Lock aRest
  value_template: "{%if value_json.return_value == 1 %}on{%elif value_json.return_value == 0 %}off{% endif %}"
  device_class: safety

- platform: rest
  resource: http://192.168.0.22:3000/digital/13
  name: PIR Staircase aRest
  value_template: "{%if value_json.return_value == 1 %}on{%elif value_json.return_value == 0 %}off{% endif %}"
  device_class: motion

- platform: rest
  resource: http://192.168.0.22:3000/digital/15
  name: PhotoResistor aRest
  value_template: "{%if value_json.return_value == 1 %}on{%elif value_json.return_value == 0 %}off{% endif %}"
  device_class: light

- platform: rest
  resource: http://192.168.0.22:3000/digital/16
  name: PIR Living Room Front aRest
  value_template: "{%if value_json.return_value == 1 %}on{%elif value_json.return_value == 0 %}off{% endif %}"
  device_class: motion

- platform: rest
  resource: http://192.168.0.22:3000/digital/22
  name: PIR Living Room Back aRest
  value_template: "{%if value_json.return_value == 1 %}on{%elif value_json.return_value == 0 %}off{% endif %}"
  device_class: motion

- platform: rest
  resource: http://192.168.0.22:3000/digital/26
  name: PIR Conservatory aRest
  value_template: "{%if value_json.return_value == 1 %}on{%elif value_json.return_value == 0 %}off{% endif %}"
  device_class: motion
