- alias: Email when CCTV Disk Error
  trigger:
  - platform: state
    entity_id: binary_sensor.front_cctv_disk_error
    to: 'on'
  action:
  - service: tts.google_say
    entity_id: media_player.mpd
    data_template:
      message: Disk Error Detected on Front CCTV.
  - service: notify.gmaillolo
    data_template:
      message: Disk Error Detected on Front CCTV.