- alias: Email when CCTV SD Card Full
  trigger:
  - platform: state
    entity_id: binary_sensor.front_cctv_disk_full
    to: 'on'
  action:
  - service: notify.gmaillolo
    data_template:
      message: SD Card on Front CCTV is full.