- alias: All Lights Off
  initial_state: true
  trigger:
    - platform: state
      entity_id: group.pirs
      to: 'off'
      for:
        minutes: 3
  condition:
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'off'
  action:
  - service: light.turn_off
    data:
      entity_id: group.Interior_Lights
  - service: switch.turn_off
    data:
      entity_id: switch.kitchen_tv
  - service: light.turn_off
    data:
      entity_id: light.conservatory_led_strip
  - delay: 00:00:01
  - service: light.turn_off
    data:
      entity_id: light.conservatory_led_strip