- alias: turn_baubles_on_1
  trigger:
    - platform: template
      value_template: '{{states.sensor.bauble_random_effect.state | int == 1 }}'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: group.pirs
        state: 'on'
      - condition: state
        entity_id: media_player.panasonic_viera_tv
        state: 'on'
    - condition: state
      entity_id: input_boolean.xmas
      state: 'on'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.photoresistor
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: light.living_room_main
        state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.bauble_1
      effect: "sparkle"
  - service: light.turn_on
    data:
      entity_id: light.bauble_2
      effect: "rainbow"
  - service: light.turn_on
    data:
      entity_id: light.bauble_3
      effect: "uniglow"

- alias: turn_baubles_on_2
  trigger:
    - platform: template
      value_template: '{{states.sensor.bauble_random_effect.state | int == 2 }}'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: group.pirs
        state: 'on'
      - condition: state
        entity_id: media_player.panasonic_viera_tv
        state: 'on'
    - condition: state
      entity_id: input_boolean.xmas
      state: 'on'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.photoresistor
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: light.living_room_main
        state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.bauble_2
      effect: "sparkle"
  - service: light.turn_on
    data:
      entity_id: light.bauble_3
      effect: "rainbow"
  - service: light.turn_on
    data:
      entity_id: light.bauble_1
      effect: "uniglow"

- alias: turn_baubles_on_3
  trigger:
    - platform: template
      value_template: '{{states.sensor.bauble_random_effect.state | int == 3 }}'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: group.pirs
        state: 'on'
      - condition: state
        entity_id: media_player.panasonic_viera_tv
        state: 'on'
    - condition: state
      entity_id: input_boolean.xmas
      state: 'on'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.photoresistor
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: light.living_room_main
        state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.bauble_3
      effect: "sparkle"
  - service: light.turn_on
    data:
      entity_id: light.bauble_1
      effect: "rainbow"
  - service: light.turn_on
    data:
      entity_id: light.bauble_2
      effect: "uniglow"

