- alias: turn_bauble_on/off
  trigger:
    - platform: state
      entity_id: input_boolean.bauble_1
    - platform: state
      entity_id: input_boolean.bauble_2
    - platform: state
      entity_id: input_boolean.bauble_3
  action:
    - service_template: >
        {% if trigger.entity_id == "input_boolean.bauble_1" %} rest_command.bauble_1_state
        {% elif trigger.entity_id == "input_boolean.bauble_2" %} rest_command.bauble_2_state
        {% else %} rest_command.bauble_3_state
        {% endif %}


- alias: set_bauble_mode
  trigger:
    - platform: state
      entity_id: input_select.bauble_1_mode
    - platform: state
      entity_id: input_select.bauble_2_mode
    - platform: state
      entity_id: input_select.bauble_3_mode
  action:
    - service_template: >
        {% if trigger.entity_id == "input_select.bauble_1_mode" %} rest_command.bauble_1_mode
        {% elif trigger.entity_id == "input_select.bauble_2_mode" %} rest_command.bauble_2_mode
        {% else %} rest_command.bauble_3_mode
        {% endif %}
    - service_template: >
        {% if trigger.entity_id == "input_select.bauble_1_mode" %} input_boolean.turn_on > data: >entity_id: input_boolean.bauble_1
        {% elif trigger.entity_id == "input_select.bauble_2_mode" %} input_boolean.turn_on > data: >entity_id: input_boolean.bauble_2
        {% else %} input_boolean.turn_on > data: >entity_id: input_boolean.bauble_3
        {% endif %}


- alias: update_bauble_status_1
  trigger:
    - platform: state
      entity_id: input_select.bauble_1_mode
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.bauble_1


- alias: update_bauble_status_2
  trigger:
    - platform: state
      entity_id: input_select.bauble_2_mode
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.bauble_2


- alias: update_bauble_status_3
  trigger:
    - platform: state
      entity_id: input_select.bauble_3_mode
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.bauble_3