- alias: Chromecast - Set Radio Volume
  initial_state: true
  trigger:
    platform: state
    entity_id: input_number.volume_radio
  action:
    service: media_player.volume_set
    data_template:
      entity_id: >
        {% if is_state("input_select.chromecast_radio_speakers", "Conservatory") %} media_player.conservatory
        {% elif is_state("input_select.chromecast_radio_speakers", "Kitchen") %} media_player.kitchen
        {% elif is_state("input_select.chromecast_radio_speakers", "Onkyo") %} media_player.onkyo_txnr656
        {% elif is_state("input_select.chromecast_radio_speakers", "House") %} media_player.house
        {% endif %}
      volume_level: '{{  states("input_number.volume_radio")  }}'