- alias: Chromecast - Set Radio Volume
  trigger:
    platform: state
    entity_id: input_number.volume_radio
  action:
    service: media_player.volume_set
    data_template:
      entity_id: >
        {% if is_state("input_select.chromecast_radio_speakers", "Conservatory") %} media_player.conservatory
        {% elif is_state("input_select.chromecast_radio_speakers", "Kitchen") %} media_player.kitchen
        {% elif is_state("input_select.chromecast_radio_speakers", "Onkyo") %} media_player.onkyo_txnr656
        {% elif is_state("input_select.chromecast_radio_speakers", "House") %} media_player.house
        {% endif %}
      volume_level: '{{  states.input_number.volume_radio.state  }}'


- alias Chromecast - Update Radio Stream Artist & Album Titles
  trigger:
    platform: state
    entity_id:
      - sensor.rtl2_artist
      - sensor.rtl2_track
      - sensor.absolute_radio_cr_artist
      - sensor.absolute_radio_cr_track
      - sensor.absolute_radio_artist
      - sensor.absolute_radio_track
      - sensor.ha_podcast_track
      - sensor.internet_of_things_podcast_track
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.stream_artist
    - service: homeassistant.update_entity
      entity_id: sensor.stream_track