- alias: Set Chromecast Radio Volume
  trigger:
    platform: state
    entity_id: input_number.volume_radio
  action:
    service: media_player.volume_set
    data_template:
      entity_id: >
        {% if is_state("input_select.chromecast_radio", "Bedroom") %} media_player.bedroom
        {% elif is_state("input_select.chromecast_radio", "Kitchen") %} media_player.kitchen
        {% elif is_state("input_select.chromecast_radio", "Onkyo") %} media_player.onkyo_txnr656_e0ee71
        {% elif is_state("input_select.chromecast_radio", "Downstairs") %} media_player.downstairs
        {% elif is_state("input_select.chromecast_radio", "House") %} media_player.house
        {% endif %}
      volume_level: '{{  states.input_number.volume_radio.state  }}'