- alias: Conservatory Window Open
  trigger:
    - platform: state
      entity_id: binary_sensor.conservatory_window
      to: 'on'
  action:
  - service: media_player.play_media
    data:
      entity_id: media_player.google_home_minis
      media_content_id: 'http://192.168.0.24/audio/RemoteOn.mp3'
      media_content_type: 'audio/mp3'

- alias: Conservatory Window Closed
  trigger:
    - platform: state
      entity_id: binary_sensor.conservatory_window
      to: 'off'
  action:
  - service: media_player.play_media
    data:
      entity_id: media_player.google_home_minis
      media_content_id: 'http://192.168.0.24/audio/RemoteOff.mp3'
      media_content_type: 'audio/mp3'


