- alias: Conservatory SkyLight Open
  trigger:
    - platform: state
      entity_id: binary_sensor.conservatory_skylight_left
      to: 'on'
  action:
  - service: media_player.play_media
    data:
      entity_id: media_player.google_home_minis
      media_content_id: 'http://192.168.0.24/audio/RemoteOn.mp3'
      media_content_type: 'audio/mp3'

- alias: Conservatory SkyLight Closed
  trigger:
    - platform: state
      entity_id: binary_sensor.conservatory_skylight_left
      to: 'off'
  action:
  - service: media_player.play_media
    data:
      entity_id: media_player.google_home_minis
      media_content_id: 'http://192.168.0.24/audio/RemoteOff.mp3'
      media_content_type: 'audio/mp3'

- alias: Conservatory SkyLight Left Open When Leaving
  trigger:
    - platform: state
      entity_id: device_tracker.div
      from: "home"
    - platform: state
      entity_id: device_tracker.lolo
      from: "home"
  condition:
    - condition: template
      value_template: '{{ states.device_tracker.lolo.state != "home"}}'
    - condition: template
      value_template: '{{ states.device_tracker.div.state != "home"}}'
    - condition: state
      entity_id: binary_sensor.conservatory_skylight_left
      state: 'on'
  action:
    - service: notify.gmaillolo
      data_template:
        message: 'Conservatory SkyLight Left Open!'

- alias: Conservatory SkyLight Left Open At Night
  trigger:
    - platform: state
      entity_id: group.pirs
      to: 'off'
  condition:
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'off'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: binary_sensor.conservatory_skylight_left
      state: 'on'
  action:
    - service: notify.gmaillolo
      data_template:
        message: 'Conservatory SkyLight Left Open!'
    - service: media_player.volume_set
      data:
        entity_id: media_player.living_room_google_mini
        volume_level: 1
    - service: media_player.volume_set
      data:
        entity_id: media_player.kitchen_google_mini
        volume_level: 1
    - service: media_player.volume_set
      data:
        entity_id: media_player.google_home_minis
        volume_level: 1
    - service: tts.google_say
      entity_id: media_player.google_home_minis
      data:
        message: 'Please note: The conservatory skylight windows are open'
    - service: media_player.volume_set
      data:
        entity_id: media_player.living_room_google_mini
        volume_level: 0.50
    - service: media_player.volume_set
      data:
        entity_id: media_player.kitchen_google_mini
        volume_level: 0.50
    - service: media_player.volume_set
      data:
        entity_id: media_player.google_home_minis
        volume_level: 0.50


