- alias: Door or Window Opens
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.conservatory_skylight_left
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00022d2c49
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002435612
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002434385
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00022d2d3d
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d000232dcd3
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d000232ddf8
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: disarmed
  action:
  - service: media_player.play_media
    data:
      entity_id: media_player.google_home_minis
      media_content_id: 'http://192.168.0.24/audio/RemoteOn.mp3'
      media_content_type: 'audio/mp3'

- alias: Door or Window Closes
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.conservatory_skylight_left
      to: 'off'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00022d2c49
      to: 'off'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002435612
      to: 'off'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0002434385
      to: 'off'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00022d2d3d
      to: 'off'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d000232dcd3
      to: 'off'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d000232ddf8
      to: 'off'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: disarmed
  action:
  - service: media_player.play_media
    data:
      entity_id: media_player.google_home_minis
      media_content_id: 'http://192.168.0.24/audio/RemoteOff.mp3'
      media_content_type: 'audio/mp3'

- alias: Conservatory SkyLight Left Open When Leaving
  initial_state: true
  trigger:
    - platform: state
      entity_id: person.laurent
      from: "home"
    - platform: state
      entity_id: person.div
      from: "home"
  condition:
    - condition: template
      value_template: '{{ states("person.laurent") != "home"}}'
    - condition: template
      value_template: '{{ states("person.div") != "home"}}'
    - condition: state
      entity_id: binary_sensor.conservatory_skylight_left
      state: 'on'
  action:
    - service: notify.gmaillolo
      data_template:
        message: 'Conservatory SkyLight Left Open!'

- alias: Conservatory SkyLight Left Open At Night
  initial_state: true
  trigger:
    - platform: state
      entity_id: group.pirs
      to: 'off'
  condition:
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'off'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: binary_sensor.conservatory_skylight_left
      state: 'on'
  action:
    - service: notify.gmaillolo
      data_template:
        message: 'Conservatory SkyLight Left Open!'
    - service: media_player.volume_set
      data:
        entity_id: media_player.living_room_google_mini
        volume_level: 1
    - service: media_player.volume_set
      data:
        entity_id: media_player.kitchen_google_mini
        volume_level: 1
    - service: media_player.volume_set
      data:
        entity_id: media_player.google_home_minis
        volume_level: 1
    - service: tts.google_say
      entity_id: media_player.google_home_minis
      data:
        message: 'Please note: The conservatory skylight windows are open'
    - service: media_player.volume_set
      data:
        entity_id: media_player.living_room_google_mini
        volume_level: 0.50
    - service: media_player.volume_set
      data:
        entity_id: media_player.kitchen_google_mini
        volume_level: 0.50
    - service: media_player.volume_set
      data:
        entity_id: media_player.google_home_minis
        volume_level: 0.50


- alias: 'Hallway Light On When Opening Main Door'
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.door_window_sensor_158d000232ddf8
      to: 'on'
  condition:
    - condition: state
      entity_id: group.pirs
      state: 'off'
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ states("sensor.aloe_vera_light_intensity") != "unknown" and  states("sensor.aloe_vera_light_intensity") | int < 250 }}'
      - condition: state
        entity_id: binary_sensor.photoresistor
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
  - service: light.turn_on
    data:
      entity_id: light.hallway
      brightness: 255


- alias: Hallway Light Off 2 min after Opening Main Door
  initial_state: true
  trigger:
    - platform: state
      entity_id: light.hallway
      to: 'on'
      for:
        minutes: 2
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.normal
        state: 'on'
      - condition: state
        entity_id: input_boolean.holidays
        state: 'on'
  action:
  - service: light.turn_off
    data:
      entity_id: light.hallway




