- alias: Mailbox Notification
  trigger:
    - platform: state
      entity_id: binary_sensor.mailbox
      to: 'on'
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.automation.mailbox_notification.attributes.last_triggered | default(0)) | int > 10 )}}'
  action:
    - service: tts.google_say
      entity_id: media_player.mpd
      data:
        message: 'Please note: post has been delivered'
    - service: shell_command.mailbox_notification_email

- alias: Reset Mailbox
  trigger:
    - platform: time
      hours: 0
      minutes: 0
      seconds: 0
  action:
    - service: shell_command.reset_mailbox





- alias: Doorbell Notification
  trigger:
    - platform: event
      event_type: signal_received
      event_data:
        entity_id: sensor.doorbell_sound
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.automation.doorbell_notification.attributes.last_triggered | default(0)) | int > 10 )}}'
  action:
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room_google_mini
      media_content_id: 'http://192.168.0.24/audio/Doorbell_Tubular_2.mp3'
      media_content_type: 'audio/mp3'
  - service: shell_command.doorbell_notification_email