- alias: Doorbell Notification
  initial_state: true
  trigger:
    - platform: event
      event_type: signal_received
      event_data:
        entity_id: sensor.doorbell_sound
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.doorbell_notification", "last_triggered") | default(0)) | int > 10 )}}'
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.google_home_minis
      volume_level: '1' 
  - service: media_player.play_media
    data:
      entity_id: media_player.google_home_minis
      media_content_id: 'http://192.168.0.24/audio/Doorbell_Tubular_2.mp3'
      media_content_type: 'audio/mp3'
  - delay: 00:00:10
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.google_home_minis
      volume_level: '{% if as_timestamp(now()) | timestamp_custom("%-H") | float >= 7 and as_timestamp(now()) | timestamp_custom("%-H") | float < 20 %} 0.75 {% else %} 0.5 {% endif %}' 
  - service: mqtt.publish
    data:
      topic: "Sensors/DoorBellEmail"
      payload_template: 'ON'
      retain: false


- alias: 'Hallway Light On When Opening Main Door'
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.door_window_sensor_158d000232ddf8
      to: 'on'
  condition:
    - condition: state
      entity_id: group.pirs
      state: 'off'
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ states("sensor.aloe_vera_light_intensity") != "unknown" and  states("sensor.aloe_vera_light_intensity") | int < 250 }}'
      - condition: state
        entity_id: binary_sensor.photoresistor
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
  - service: light.turn_on
    data:
      entity_id: light.hallway
      brightness: 255
