- alias: Edimax - Battery Is Charged
  trigger:
    - platform: state
      entity_id: sensor.edimax1_watts
  condition:
    - condition: template
      value_template: '{{ states.sensor.edimax1_watts.state | int < 1 }}'
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.automation.hass_start_sound.attributes.last_triggered | default(0))) | int > 90}}'
  action:
    - delay: '0:0:30'
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.automation.hass_start_sound.attributes.last_triggered | default(0))) | int > 90}}'
    - condition: state
      entity_id: input_boolean.silent
      state: "off"
    - service: tts.google_say
      entity_id: media_player.google_home_minis
      data:
        message: 'Please note: The battery is charged'