- alias: Free Ram
  initial_state: true
  trigger:
    - platform: template
      value_template: '{{ states("sensor.ram_usage") |int > 70}}'
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.ram_too_high", "last_triggered") | default(0)) | int > 3600 )}}'
  action:
    - service: shell_command.freeram