- alias: Play Good Morning
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_living_room_front
      to: 'on'
  condition:
    - condition: time
      after: '06:00'
      before: '12:00'
    - condition: template
      # Only run if more than 6 hours (21,600 sec) since it last ran 
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.automation.play_good_morning.attributes.last_triggered | default(0)) | int > 21600 )}}'
  action:
    # - service: shell_command.play_good_morning
    - service: tts.google_say
      data_template:
        entity_id: media_player.living_room_google_mini
        message: >
          {{["Good morning.","Hello.","Greetings.","Hi."] | random}} It's currently {{states.sensor.dark_sky_summary.state}} and {{states.sensor.dark_sky_temperature.state|round}} degrees. Today will be {{states.sensor.dark_sky_hourly_summary.state|replace(".", "")}}, highs: {{states.sensor.dark_sky_daily_high_temperature.state|round}}, lows: {{states.sensor.dark_sky_daily_low_temperature.state|round}}. Maximum precipitation intensity: {{(states.sensor.dark_sky_daily_max_precip_intensity.state | float * 10) | round(1)}} millimeters. {% if now().strftime("%a") == 'Mon' or now().strftime("%a") == 'Tue' or now().strftime("%a") == 'Thu' %}Estimated travel time to Waybridge: {{states.sensor.home_to_verint.state}} minutes.{% endif %} {% if now().strftime("%a") == 'Mon' or now().strftime("%a") == 'Wed' or now().strftime("%a") == 'Fri' %} Remember to empy the vacuum. {% endif %}{% if as_timestamp(now()) | timestamp_custom('%Y-%m-%d') == (states.calendar.birthdays__events.attributes.start_time).split(" ")[0]%} Your next appointment is: {{states.calendar.birthdays__events.attributes.message}} at {{(states.calendar.birthdays__events.attributes.start_time).split(" ")[1].split(":")[0]}} {%if (states.calendar.birthdays__events.attributes.start_time).split(" ")[1].split(":")[1] != '00'%}{{(states.calendar.birthdays__events.attributes.start_time).split(" ")[1].split(":")[1]}} {%endif%} {%endif%}
