- alias: HASS Update Available Notification
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    - service: notify.gmaillolo
      data_template:
        message: |
          There is an update to HomeAssistant: V{{states.updater.updater.state}}
          Release Notes: {{ states.updater.updater.attributes.release_notes.split("0-")[0]+states.updater.updater.attributes.release_notes.split("0-")[1] }}

- alias: HASS Start
  trigger:
    - platform: homeassistant
      event: start
  action:
  - service: shell_command.play_mp3
    data_template:
      File: 'Click.mp3'
  - service: shell_command.getcurrentcost

- alias: HASS Stop
  trigger:
    - platform: event
      event_type: homeassistant_stop
  action:
  - service: shell_command.play_mp3
    data_template:
      File: 'ClickOff.mp3'


- alias: HASS Restart
  trigger:
    - platform: state
      entity_id: input_boolean.hass_restart
      to: 'on'
  action:
  - service: shell_command.restart_hass

- alias: 'Auto Renew SSL Cert'
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 29
  action:
    service: shell_command.renew_ssl

- alias: 'SSL expiry notification'
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 21
  action:
    service: notify.gmaillolo
    data:
      message: 'Warning - SSL certificate expires in 21 days and has not been automatically renewed'