- alias: HASS Update Available Notification
  trigger:
    platform: state
    entity_id: sensor.ha_online_version
  condition:
    - condition: template
      value_template: '{{states.sensor.ha_online_version.state != states.sensor.current_version.state }}'
  action:
    - service: notify.gmaillolo
      data_template:
        message: 'There is an update to Home-Assistant: {{states.sensor.ha_online_version.state}}'

- alias: HASS Start Sound
  trigger:
    - platform: homeassistant
      event: start
  action:
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room_google_mini
      media_content_id: 'http://192.168.0.24/audio/Click.mp3'
      media_content_type: 'audio/mp3'

- alias: HASS Stop Motion Detection
  trigger:
    - platform: homeassistant
      event: start
  action:
  - service: switch.turn_off
    entity_id: switch.dafang_living_room_status
  # - service: switch.turn_on
    # entity_id: switch.dafang_living_room_yellow_led
  - service: switch.turn_off
    entity_id: switch.dafang_kitchen_status
  # - service: switch.turn_on
    # entity_id: switch.dafang_kitchen_yellow_led


# - alias: HASS Start PlexDNS
  # trigger:
    # - platform: homeassistant
      # event: start
  # action:
  # - service: shell_command.plexdns


# - alias: HASS Start CurrentCost
  # trigger:
    # - platform: homeassistant
      # event: start
  # action:
  # - service: shell_command.getcurrentcost

- alias: HASS Stop Sound
  trigger:
    - platform: event
      event_type: homeassistant_stop
  action:
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room_google_mini
      media_content_id: 'http://192.168.0.24/audio/ClickOff.mp3'
      media_content_type: 'audio/mp3'
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room_google_mini
      media_content_id: 'http://192.168.0.24/audio/ClickOff.mp3'
      media_content_type: 'audio/mp3'

- alias: HASS Restart Button
  trigger:
    - platform: state
      entity_id: input_boolean.hass_restart
      to: 'on'
  action:
  - service: shell_command.restart_hass

- alias: HASS Nightly Restart
  trigger:
    platform: time
    hours: 2
    minutes: 0
    seconds: 0
  action:
  - service: shell_command.reboot_dafang_kitchen
  - service: shell_command.reboot_dafang_livingroom
  - service: shell_command.restart_hass


- alias: 'Auto Renew SSL Cert'
  trigger:
    platform: template
    value_template: '{{ states.sensor.ssl_cert_expiry.state | int < 29 }}'
  action:
    service: shell_command.renew_ssl

- alias: 'SSL expiry notification'
  trigger:
    platform: template
    value_template: '{{ states.sensor.ssl_cert_expiry.state | int < 21 }}'
  action:
    service: notify.gmaillolo
    data:
      message: 'Warning - SSL certificate expires in 21 days and has not been automatically renewed'



- alias: HASS Start Xmas Setup
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: group.set_visibility
      entity_id: group.xmas
      data:
        visible: False
    - condition: template
      value_template: '{{ (as_timestamp(now()) -(states.input_datetime.xmas_start.attributes.timestamp | default(0)) | int > 0)}}'
    - condition: template
      value_template: '{{ ((states.input_datetime.xmas_end.attributes.timestamp | default(0)) | int ) - as_timestamp(now()) >0 }}'
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.xmas
    - service: group.set_visibility
      entity_id: group.xmas
      data_template:
        visible: >
          {% if is_state("input_boolean.xmas", "on") %}True
          {% else %}False
          {% endif %}
        
