- alias: Holiday Start
  initial_state: true
  trigger:
    - platform: state
      entity_id: device_tracker.div
      from: "home"
    - platform: state
      entity_id: device_tracker.lolo
      from: "home"
  condition:
    - condition: template
      value_template: '{{ (as_timestamp(now()) -(state_attr("input_datetime.holiday_start", "timestamp") | default(0)) | int > 0)}}'
    - condition: template
      value_template: '{{ ((state_attr("input_datetime.holiday_end", "timestamp") | default(0)) | int) - as_timestamp(now()) > 0 }}'
    - condition: template
      value_template: '{{ states("device_tracker.lolo") != "home"}}'
    - condition: template
      value_template: '{{ states("device_tracker.div") != "home"}}'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.holidays

- alias: Holiday End
  initial_state: true
  trigger:
    - platform: state
      entity_id: group.pirs
      to: 'on'
    - platform: state
      entity_id: 'device_tracker.lolos_iphone'
    - platform: state
      entity_id: 'device_tracker.google_maps_110345542315981072615'
    - platform: state
      entity_id: 'device_tracker.laurent_mah_iphone_5s'
    - platform: state
      entity_id: device_tracker.div_iphone
    - platform: state
      entity_id: device_tracker.google_maps_113578038090869627198
  condition:
    - condition: template
      value_template: '{{ (as_timestamp(now()) -(state_attr("input_datetime.holiday_end", "timestamp") | default(0)) | int > 0)}}'
    - condition: state
      entity_id: 'input_boolean.holidays'
      state: "on"
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ distance(states.device_tracker.lolos_iphone) | int  < 3}}'
      - condition: template
        value_template: '{{ distance(states.device_tracker.google_maps_110345542315981072615) | int  < 3}}'
      - condition: template
        value_template: '{{ distance(states.device_tracker.laurent_mah_iphone_5s) | int  < 3}}'
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ distance(states.device_tracker.div_iphone) | int  < 3}}'
      - condition: template
        value_template: '{{ distance(states.device_tracker.google_maps_113578038090869627198) | int  < 3}}'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.normal




- alias: Holiday Living Room
  initial_state: true
  trigger:
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
  condition:
    - condition: state
      entity_id: 'input_boolean.holidays'
      state: "on"
  action:
  - delay: "{{range(0,300+1)|random|timestamp_custom('%X',false)}}"
  - service: light.turn_on
    data:
      entity_id: light.living_room_main
      brightness: 255
  - service: light.turn_on
    data:
      entity_id: light.kitchen_window
      brightness: 255



- alias: Holiday Upstairs on
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: 22
      minutes: 30
      seconds: 0
  condition:
    - condition: state
      entity_id: 'input_boolean.holidays'
      state: "on"
  action:
  - delay: "{{range(0,1200+1)|random|timestamp_custom('%X',false)}}"
  - service: switch.turn_on
    data:
      entity_id: switch.LWRF_Socket_3
  - service: light.turn_on
    data:
      entity_id: light.kiaan_lamp
      brightness: 255
      effect: "solid"
      rgb_color: [255,255,255]
  - delay: "{{range(0,300+1)|random|timestamp_custom('%X',false)}}"
  - service: light.turn_off
    data:
      entity_id: light.living_room_main
  - delay: "{{range(0,300+1)|random|timestamp_custom('%X',false)}}"
  - service: light.turn_off
    data:
      entity_id: light.kitchen_window


- alias: Holiday Upstairs off
  initial_state: true
  trigger:
    - platform: time_pattern
      hours: 23
      minutes: 0
      seconds: 0
  condition:
    - condition: state
      entity_id: 'input_boolean.holidays'
      state: "on"
  action:
  - delay: "{{range(0,1200+1)|random|timestamp_custom('%X',false)}}"
  - service: switch.turn_off
    data:
      entity_id: switch.LWRF_Socket_3
  - service: light.turn_off
    data:
      entity_id: light.living_room_main
  - service: light.turn_off
    data:
      entity_id: light.kitchen_window
  - service: light.turn_off
    data:
      entity_id: light.kiaan_lamp



