- alias: Holiday Start
  trigger:
    - platform: zone
      entity_id: device_tracker.zevsmpjl_div_iphone
      zone: zone.home
      event: leave
    - platform: zone
      entity_id: device_tracker.zevsmpjl_lolo_iphone
      zone: zone.home
      event: leave
  condition:
    - condition: template
      value_template: '{{ (as_timestamp(now()) -(states.input_datetime.holiday_start.attributes.timestamp | default(0)) | int > 0)}}'
    - condition: template
      value_template: '{{ ((states.input_datetime.holiday_end.attributes.timestamp | default(0)) | int) - as_timestamp(now()) > 0 }}'
    - condition: template
      value_template: '{{ states.device_tracker.zevsmpjl_lolo_iphone.state != "home"}}'
    - condition: template
      value_template: '{{ states.device_tracker.zevsmpjl_div_iphone.state != "home"}}'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.holidays

- alias: Holiday End
  trigger:
    - platform: state
      entity_id: group.pirs
      to: 'on'
  condition:
    - condition: template
      value_template: '{{ (as_timestamp(now()) -(states.input_datetime.holiday_end.attributes.timestamp | default(0)) | int > 0)}}'
    - condition: state
      entity_id: 'input_boolean.holidays'
      state: "on"
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.holidays




- alias: Holiday Living Room
  trigger:
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
    - platform: state
      entity_id: binary_sensor.photoresistor
      to: 'off'
  condition:
    - condition: state
      entity_id: 'input_boolean.holidays'
      state: "on"
  action:
  - service: light.turn_on
    data:
      entity_id: light.living_room_main
      brightness: 255
  - service: light.turn_on
    data:
      entity_id: light.kitchen_window
      brightness: 255



- alias: Holiday Upstairs on
  trigger:
    - platform: time
      hours: 22
      minutes: 34
      seconds: 0
  condition:
    - condition: state
      entity_id: 'input_boolean.holidays'
      state: "on"
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.LWRF_Socket_3
  - service: light.turn_off
    data:
      entity_id: light.living_room_main
  - service: light.turn_off
    data:
      entity_id: light.kitchen_window


- alias: Holiday Upstairs off
  trigger:
    - platform: time
      hours: 23
      minutes: 04
      seconds: 0
  condition:
    - condition: state
      entity_id: 'input_boolean.holidays'
      state: "on"
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.LWRF_Socket_3
  - service: light.turn_off
    data:
      entity_id: light.living_room_main
  - service: light.turn_off
    data:
      entity_id: light.kitchen_window



