- alias: Notify iOS app
  trigger:
    - platform: state
      entity_id: alert.basil_battery_too_low
      from: 'idle'
      to: 'on'
    - platform: state
      entity_id: alert.basil_humidity_too_low
      from: 'idle'
      to: 'on'
    - platform: state
      entity_id: alert.cctv_dafang_kitchen_lost
      from: 'idle'
      to: 'on'
    - platform: state
      entity_id: alert.cctv_dafang_living_room_lost
      from: 'idle'
      to: 'on'
    - platform: state
      entity_id: alert.cctv_front_lost
      from: 'idle'
      to: 'on'
    - platform: state
      entity_id: alert.cctv_garage_lost
      from: 'idle'
      to: 'on'
    - platform: state
      entity_id: alert.currentcost_lost
      from: 'idle'
      to: 'on'
    - platform: state
      entity_id: alert.dehumidifier_full
      from: 'idle'
      to: 'on'
    - platform: state
      entity_id: alert.home_disk_usage_too_high
      from: 'idle'
      to: 'on'
    - platform: state
      entity_id: alert.house_number_led_strip_lost
      from: 'idle'
      to: 'on'
    - platform: state
      entity_id: alert.outside_temp_sensor_lost
      from: 'idle'
      to: 'on'
    - platform: state
      entity_id: alert.ram_too_high
      from: 'idle'
      to: 'on'
    - platform: state
      entity_id: alert.root_disk_usage_too_high
      from: 'idle'
      to: 'on'
    - platform: state
      entity_id: alert.rpi_lost
      from: 'idle'
      to: 'on'
    - platform: state
      entity_id: alert.rpi_zero_w_lost
      from: 'idle'
      to: 'on'
    - platform: state
      entity_id: alert.staircase_led_strip_lost
      from: 'idle'
      to: 'on'
    - platform: state
      entity_id: alert.tv_cabinet_led_strip_lost
      from: 'idle'
      to: 'on'
    - platform: state
      entity_id: alert.upstairs_temp_sensor_lost
      from: 'idle'
      to: 'on'
  action:
    - service: counter.increment
      entity_id: counter.iosbadgecount
    - service: notify.ios_lolos_iphone
      data_template:
        message: '{{ trigger.entity_id | replace("alert.","") | replace("_"," ") |capitalize }}'
        data:
          push:
            badge: '{{states.counter.iosbadgecount.state}}'
            category: "alert"
          action_data:
            entity_id: '{{trigger.entity_id}}'

- alias: Turn Alert Off
  trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: DISABLE_ALERT
  action:
    - service: alert.turn_off
      data_template:
        entity_id: '{{ trigger.event.data["action_data"]["entity_id"] }}'

- alias: Decrease Counter with Alert to Idle
  trigger:
    - platform: state
      entity_id: alert.basil_battery_too_low
      to: 'idle'
    - platform: state
      entity_id: alert.basil_humidity_too_low
      to: 'idle'
    - platform: state
      entity_id: alert.cctv_dafang_kitchen_lost
      to: 'idle'
    - platform: state
      entity_id: alert.cctv_dafang_living_room_lost
      to: 'idle'
    - platform: state
      entity_id: alert.cctv_front_lost
      to: 'idle'
    - platform: state
      entity_id: alert.cctv_garage_lost
      to: 'idle'
    - platform: state
      entity_id: alert.currentcost_lost
      to: 'idle'
    - platform: state
      entity_id: alert.dehumidifier_full
      to: 'idle'
    - platform: state
      entity_id: alert.home_disk_usage_too_high
      to: 'idle'
    - platform: state
      entity_id: alert.house_number_led_strip_lost
      to: 'idle'
    - platform: state
      entity_id: alert.outside_temp_sensor_lost
      to: 'idle'
    - platform: state
      entity_id: alert.ram_too_high
      to: 'idle'
    - platform: state
      entity_id: alert.root_disk_usage_too_high
      to: 'idle'
    - platform: state
      entity_id: alert.rpi_lost
      to: 'idle'
    - platform: state
      entity_id: alert.rpi_zero_w_lost
      to: 'idle'
    - platform: state
      entity_id: alert.staircase_led_strip_lost
      to: 'idle'
    - platform: state
      entity_id: alert.tv_cabinet_led_strip_lost
      to: 'idle'
    - platform: state
      entity_id: alert.upstairs_temp_sensor_lost
      to: 'idle'
  action:
    - service: counter.decrement
      entity_id: counter.iosbadgecount