- alias: TV Cabinet LED Strip On PIR
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_living_room_front
      to: 'on'
    - platform: state
      entity_id: binary_sensor.pir_living_room_back
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.xmas
      state: 'off'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.TV_Cabinet_LED_Strip
      brightness: 255
      rgb_color: [0,255,0]
      transition: 1
  - service: light.turn_on
    data:
      entity_id: light.TV_Cabinet_LED_Strip
      brightness: 255
      rgb_color: [0,255,0]



- alias: TV Cabinet LED Strip On Xmas
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_living_room_front
      to: 'on'
    - platform: state
      entity_id: binary_sensor.pir_living_room_back
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.xmas
      state: 'on'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.TV_Cabinet_LED_Strip
      brightness: 255
      effect: colorfade_fast



- alias: Flash Alert
  trigger:
    - platform: state
      entity_id: alert.cctv_front_lost
      to: 'on'
    - platform: state
      entity_id: alert.cctv_garage_lost
      to: 'on'
    - platform: state
      entity_id: alert.currentcost_lost
      to: 'on'
    - platform: state
      entity_id: alert.dehumidifier_full
      to: 'on'
    - platform: state
      entity_id: alert.home_disk_usage_too_high
      to: 'on'
    - platform: state
      entity_id: alert.kello_lost
      to: 'on'
    - platform: state
      entity_id: alert.outside_temp_sensor_lost
      to: 'on'
    - platform: state
      entity_id: alert.ram_too_high
      to: 'on'
    - platform: state
      entity_id: alert.root_disk_usage_too_high
      to: 'on'
    - platform: state
      entity_id: alert.rpi_lost
      to: 'on'
    - platform: state
      entity_id: alert.rpi_zero_w_lost
      to: 'on'
    - platform: state
      entity_id: alert.staircase_led_strip_lost
      to: 'on'
    - platform: state
      entity_id: alert.tv_cabinet_led_strip_lost
      to: 'on'
    - platform: state
      entity_id: alert.upstairs_temp_sensor_lost
      to: 'on'
    - platform: state
      entity_id: binary_sensor.mailbox
      to: 'on'
    - platform: event
      event_type: signal_received
      event_data:
        entity_id: sensor.doorbell_sound
  action:
  - service: light.turn_on
    data:
      entity_id: light.TV_Cabinet_LED_Strip
      brightness: 255
      rgb_color: [255,0,0]
      effect: flash




- alias: TV Cabinet LED Strip Off by PIR
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_living_room_front
      to: 'off'
    - platform: state
      entity_id: binary_sensor.pir_living_room_back
      to: 'off'
  condition:
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'off'
    - condition: state
      entity_id: binary_sensor.pir_living_room_front
      state: 'off'
    - condition: state
      entity_id: binary_sensor.pir_living_room_back
      state: 'off'
  action:
  - service: light.turn_on
    data:
      entity_id: light.TV_Cabinet_LED_Strip
      brightness: 255
      rgb_color: [0,0,0]
      transition: 1
  - delay: 00:00:01
  - service: light.turn_off
    data:
      entity_id: light.TV_Cabinet_LED_Strip




- alias: Staircase LED Strip On by PIR
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_staircase
      to: 'on'
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
    - platform: state
      entity_id: binary_sensor.photoresistor
      to: 'off'
  condition:
    - condition: state
      entity_id: light.Staircase_LED_Strip
      state: 'off'
    - condition: state
      entity_id: binary_sensor.pir_staircase
      state: 'on'
    - condition: state
      entity_id: input_boolean.xmas
      state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.photoresistor
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: light.living_room_main
        state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.Staircase_LED_Strip
      brightness: 255
      rgb_color: [0,128,255]
      transition: 1


- alias: Staircase LED Strip Off by PIR
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_staircase
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.xmas
      state: 'off'
  action:
  - service: light.turn_on
    data:
      entity_id: light.Staircase_LED_Strip
      rgb_color: [0,0,0]
      transition: 1
  - delay: 00:00:01
  - service: light.turn_off
    data:
      entity_id: light.Staircase_LED_Strip





- alias: Staircase LED Strip On by PIR Xmas
  trigger:
    - platform: state
      entity_id: group.pirs
      to: 'on'
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
    - platform: state
      entity_id: binary_sensor.photoresistor
      to: 'off'
  condition:
    - condition: state
      entity_id: light.Staircase_LED_Strip
      state: 'off'
    - condition: state
      entity_id: binary_sensor.pir_staircase
      state: 'on'
    - condition: state
      entity_id: input_boolean.xmas
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.photoresistor
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: light.living_room_main
        state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.Staircase_LED_Strip
      brightness: 255
      effect: colorfade_fast

- alias: Staircase LED Strip Off by PIR Xmas
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_staircase
      to: 'off'
  condition:
    - condition: time
      after: '22:30'
      before: '08:00'
    - condition: state
      entity_id: input_boolean.xmas
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.Staircase_LED_Strip
      rgb_color: [0,0,0]
      transition: 1
  - delay: 00:00:01
  - service: light.turn_off
    data:
      entity_id: light.Staircase_LED_Strip






- alias: House Number On
  trigger:
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
  action:
  - service: light.turn_on
    data:
      entity_id: light.House_Number_LED_Strip
      brightness: 255
      effect: colorfade_slow



- alias: House Number Off
  trigger:
    - platform: time
      hours: 0
      minutes: 0
      seconds: 0
  action:
  - service: light.turn_on
    data:
      entity_id: light.House_Number_LED_Strip
      rgb_color: [0,0,0]
      transition: 1
  - delay: 00:00:01
  - service: light.turn_off
    data:
      entity_id: light.House_Number_LED_Strip