- alias: LWRF Remote 1 On
  trigger:
    - platform: event
      event_type: button_pressed
      event_data:
        entity_id: switch.lwrf_remote_1
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.automation.lwrf_remote_1_on.attributes.last_triggered | default(0)) | int > 2 )}}'
    - condition: state
      entity_id: switch.lwrf_remote_1
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: group.kitchen
      brightness: 255
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room_google_mini
      media_content_id: 'http://192.168.0.24/audio/RemoteOn.mp3'
      media_content_type: 'audio/mp3'


- alias: LWRF Remote 1 Off
  trigger:
    - platform: event
      event_type: button_pressed
      event_data:
        entity_id: switch.lwrf_remote_1
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.automation.lwrf_remote_1_off.attributes.last_triggered | default(0)) | int > 2 )}}'
    - condition: state
      entity_id: switch.lwrf_remote_1
      state: 'off'
  action:
  - service: light.turn_off
    data:
      entity_id: group.kitchen
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room_google_mini
      media_content_id: 'http://192.168.0.24/audio/RemoteOff.mp3'
      media_content_type: 'audio/mp3'



- alias: LWRF Remote 2 On
  trigger:
    - platform: event
      event_type: button_pressed
      event_data:
        entity_id: switch.lwrf_remote_2
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.automation.lwrf_remote_2_on.attributes.last_triggered | default(0)) | int > 2 )}}'
    - condition: state
      entity_id: switch.lwrf_remote_2
      state: 'on'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.kitchen_tv
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room_google_mini
      media_content_id: 'http://192.168.0.24/audio/RemoteOn.mp3'
      media_content_type: 'audio/mp3'

- alias: LWRF Remote 2 Off
  trigger:
    - platform: event
      event_type: button_pressed
      event_data:
        entity_id: switch.lwrf_remote_2
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.automation.lwrf_remote_2_off.attributes.last_triggered | default(0)) | int > 2 )}}'
    - condition: state
      entity_id: switch.lwrf_remote_2
      state: 'off'
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.kitchen_tv
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room_google_mini
      media_content_id: 'http://192.168.0.24/audio/RemoteOff.mp3'
      media_content_type: 'audio/mp3'
