- alias: Nest Remove Away Mode
  initial_state: true
  trigger:
    # - platform: state
      # entity_id: binary_sensor.hallway_thermostat_has_leaf
      # to: 'on'
    - platform: state
      entity_id: group.pirs
      to: 'on'
    - platform: state
      entity_id: person.div
      to: "home"
    - platform: state
      entity_id: person.laurent
      to: "home"
    - platform: state
      entity_id: group.door_and_window_sensors
      to: 'off'
  condition:
    - condition: state
      entity_id: climate.hallway
      state: 'eco'
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ states("person.laurent") == "home"}}'
      - condition: template
        value_template: '{{ states("person.div") == "home"}}'
    - condition: state
      entity_id: group.door_and_window_sensors
      state: 'off'
  action:
    - service: climate.set_away_mode
      data:
        entity_id: climate.hallway
        away_mode: 'off'
    - service: climate.set_temperature
      data_template:
        entity_id: climate.hallway
        temperature: '{% if states("sensor.season") == "summer" or states("sensor.season") == "spring" %}18{% else %}20{% endif %}'
        operation_mode: Heat


- alias: Nest Set Away Mode
  initial_state: true
  trigger:
    - platform: state
      entity_id: person.laurent
      from: "home"
    - platform: state
      entity_id: person.div
      from: "home"
    - platform: state
      entity_id: climate.hallway
      to: "heat"
    - platform: state
      entity_id: group.door_and_window_sensors
      to: 'on'
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: climate.hallway
      state: 'heat'
    - condition: state
      entity_id: 'input_boolean.normal'
      state: "on"
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ states("person.laurent") != "home" and states("person.div") != "home"}}'
      - condition: state
        entity_id: group.door_and_window_sensors
        state: 'on'
  action:
    - service: climate.set_away_mode
      data:
        entity_id: climate.hallway
        away_mode: 'on'
    # - service: climate.set_temperature
      # data:
        # entity_id: climate.hallway
        # temperature: 16
        # operation_mode: Heat