- alias: Nest Remove Leaf
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_thermostat_has_leaf
      to: 'on'
    - platform: state
      entity_id: group.pirs
      to: 'on'
    - platform: state
      entity_id: person.div
      to: "home"
    - platform: state
      entity_id: person.laurent
      to: "home"
  condition:
    - condition: state
      entity_id: binary_sensor.hallway_thermostat_has_leaf
      state: 'on'
    - condition: time
      after: '08:00:00'
    - condition: time
      before: '20:00:00'
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ states("person.laurent") == "home"}}'
      - condition: template
        value_template: '{{ states("person.div") == "home"}}'
  action:
    - service: climate.set_away_mode
      data:
        entity_id: climate.hallway
        away_mode: 'off'
    - service: climate.set_temperature
      data_template:
        entity_id: climate.hallway
        temperature: '{% if states("sensor.season") == "summer" or states("sensor.season") == "spring" %}18{% else %}20{% endif %}'
        operation_mode: Heat


- alias: Nest Set Leaf
  initial_state: true
  trigger:
    - platform: state
      entity_id: person.laurent
      from: "home"
    - platform: state
      entity_id: person.div
      from: "home"
  condition:
    - condition: state
      entity_id: binary_sensor.hallway_thermostat_has_leaf
      state: 'off'
    - condition: time
      after: '06:00:00'
    - condition: time
      before: '16:00:00'
    - condition: state
      entity_id: 'input_boolean.normal'
      state: "on"
    - condition: template
      value_template: '{{ states("person.laurent") != "home"}}'
    - condition: template
      value_template: '{{ states("person.div") != "home"}}'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.hallway
        temperature: 16
        operation_mode: Heat