- alias: Set Onkyo Zone 2 Volume
  trigger:
    platform: state
    entity_id: input_number.onkyo_zone2_volume
  condition:
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.Get_onkyo_zone_2_volume.attributes.last_triggered | default(0)) | int > 5)}}'
  action:
    service: shell_command.onkyo_zone2_set_volume

- alias: Get Onkyo Zone 2 Volume
  trigger:
    platform: state
    entity_id: sensor.onkyo_zone2_volume
  condition:
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.set_onkyo_zone_2_volume.attributes.last_triggered | default(0)) | int > 5)}}'
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.onkyo_zone2_volume
      value: "{{ states.sensor.onkyo_zone2_volume.state }}"