- alias: Conservatory Lights On PIR
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_conservatory
      to: 'on'
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
    - platform: state
      entity_id: binary_sensor.photoresistor
      to: 'off'
    - platform: state
      entity_id: sensor.aloe_vera_light_intensity
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.normal
        state: 'on'
      - condition: state
        entity_id: input_boolean.movies
        state: 'on'
    - condition: state
      entity_id: binary_sensor.pir_conservatory
      state: 'on'
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ states("sensor.aloe_vera_light_intensity") != "unknown" and  states("sensor.aloe_vera_light_intensity") | int < 250 }}'
      - condition: state
        entity_id: binary_sensor.photoresistor
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: light.living_room_main
        state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.conservatory
      brightness: 255



- alias: Conservatory Lights Dimmed Off PIR
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_conservatory
      to: 'off'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.normal
        state: 'on'
      - condition: state
        entity_id: input_boolean.movies
        state: 'on'
    - condition: state
      entity_id: light.conservatory
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.conservatory
      brightness: 11


- alias: Conservatory Lights Off PIR
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_conservatory
      to: 'off'
      for:
        minutes: 2
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.normal
        state: 'on'
      - condition: state
        entity_id: input_boolean.movies
        state: 'on'
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.conservatory_lights_dimmed_off_pir", "last_triggered") | default(0)) | int > 120 )}}'
    - condition: state
      entity_id: binary_sensor.pir_conservatory
      state: 'off'
    - condition: state
      entity_id: light.conservatory
      state: 'on'
  action:
  - service: light.turn_off
    data:
      entity_id: light.conservatory


- alias: Conservatory LED Lights On PIR
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_conservatory
      to: 'on'
    - platform: state
      entity_id: binary_sensor.pir_kitchen
      to: 'on'
    - platform: state
      entity_id: binary_sensor.pir_living_room_front
      to: 'on'
    - platform: state
      entity_id: binary_sensor.pir_living_room_back
      to: 'on'
    - platform: state
      entity_id: binary_sensor.photoresistor
      to: 'off'
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
    - platform: state
      entity_id: sensor.aloe_vera_light_intensity
  condition:
    - condition: state
      entity_id: light.conservatory_led_strip
      state: 'off'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: state
      entity_id: group.pirs
      state: 'on'
    - condition: or
      conditions:
      - condition: template
        value_template: '{{ states("sensor.aloe_vera_light_intensity") != "unknown" and  states("sensor.aloe_vera_light_intensity") | int < 250 }}'
      - condition: state
        entity_id: binary_sensor.photoresistor
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: light.living_room_main
        state: 'on'
    - condition: state
      entity_id: input_boolean.xmas
      state: 'off'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.conservatory_led_strip
      effect: "solid"
      brightness: 128
      rgb_color: [255,255,255]
  - service: light.turn_on
    data:
      entity_id: light.conservatory_led_strip
      effect: "solid"
      brightness: 128
      rgb_color: [255,255,255]

