# - alias: Conservatory Lights On PIR
  # trigger:
    # - platform: state
      # entity_id: binary_sensor.pir_conservatory
      # to: 'on'
    # - platform: state
      # entity_id: sun.sun
      # to: 'below_horizon'
    # - platform: state
      # entity_id: binary_sensor.photoresistor
      # to: 'off'
  # condition:
    # - condition: state
      # entity_id: binary_sensor.pir_conservatory
      # state: 'on'
    # - condition: or
      # conditions:
      # - condition: state
        # entity_id: binary_sensor.photoresistor
        # state: 'off'
      # - condition: state
        # entity_id: sun.sun
        # state: 'below_horizon'
      # - condition: state
        # entity_id: light.living_room_main
        # state: 'on'
  # action:
  # - service: switch.turn_on
    # data:
      # entity_id: switch.conservatory




# - alias: Conservatory Lights Off PIR
  # trigger:
    # - platform: state
      # entity_id: binary_sensor.pir_conservatory
      # to: 'off'
  # condition:
    # - condition: state
      # entity_id: switch.conservatory
      # state: 'on'
  # action:
  # - service: switch.turn_off
    # data:
      # entity_id: switch.conservatory




- alias: Conservatory Lights On PIR
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_conservatory
      to: 'on'
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
    - platform: state
      entity_id: binary_sensor.photoresistor
      to: 'off'
  condition:
    - condition: state
      entity_id: binary_sensor.pir_conservatory
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.photoresistor
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: light.living_room_main
        state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.conservatory
      brightness: 255
  - service: light.turn_on
    data:
      entity_id: light.conservatory_led_strip
      effect: "solid"
      brightness: 128
      rgb_color: [255,199,145]


- alias: Conservatory Lights Dimmed Off PIR
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_conservatory
      to: 'off'
  condition:
    - condition: state
      entity_id: light.conservatory
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.conservatory
      brightness: 11


- alias: Conservatory Lights Off PIR
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_conservatory
      to: 'off'
      for:
        minutes: 2
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.automation.conservatory_lights_dimmed_off_pir.attributes.last_triggered | default(0)) | int > 120 )}}'
    - condition: state
      entity_id: binary_sensor.pir_conservatory
      state: 'off'
    - condition: state
      entity_id: light.conservatory
      state: 'on'
  action:
  - service: light.turn_off
    data:
      entity_id: light.conservatory
  - delay: 00:00:05
  - service: light.turn_off
    data:
      entity_id: light.conservatory_led_strip




- alias: Conservatory LED Lights On PIR
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_conservatory
      to: 'on'
    - platform: state
      entity_id: binary_sensor.pir_kitchen
      to: 'on'
    - platform: state
      entity_id: binary_sensor.pir_living_room_front
      to: 'on'
    - platform: state
      entity_id: binary_sensor.pir_living_room_back
      to: 'on'
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
  condition:
    # - condition: state
      # entity_id: binary_sensor.pir_conservatory
      # state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.photoresistor
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: light.living_room_main
        state: 'on'
    - condition: state
      entity_id: input_boolean.xmas
      state: 'off'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.conservatory_led_strip
      effect: "solid"
      brightness: 128
      rgb_color: [255,255,255]

