- alias: Tell Div Lolo left work
  initial_state: true
  trigger:
    platform: state
    entity_id: person.laurent
    from: "Verint"
  condition:
  - condition: time
    after: '15:30:00'
  action:
    service: notify.gmaildiv
    data_template:
      message: 'Lolo left work. Estimated arrival time: {{(as_timestamp(now()) + (states("sensor.lolo_to_home") | default(0) | int)*60) | timestamp_custom("%H:%M")}}'



- alias: Tell Div Lolo reached work
  initial_state: true
  trigger:
    platform: state
    entity_id: person.laurent
    to: "Verint"
  condition:
  - condition: time
    before: '10:00:00'
  action:
    service: notify.gmaildiv
    data_template:
      message: 'Lolo reached work.'


- alias: Tell Lolo Div left work
  initial_state: true
  trigger:
    platform: state
    entity_id: person.div
    from: "CBC"
  condition:
  - condition: time
    after: '16:00:00'
  action:
    - service: notify.gmaillolo
      data_template:
        message: 'Div left work. ETA: {{states("sensor.div_to_home")}} min.'
    - condition: state
      entity_id: input_boolean.silent
      state: "off"
    - service: tts.google_say
      entity_id: media_player.google_home_minis
      data:
        message: 'Please note: Div left work'


- alias: Tell Lolo Div left yoga
  initial_state: true
  trigger:
    - platform: state
      entity_id: person.div
      from: "Ifield College"
    - platform: state
      entity_id: person.div
      from: "Oriel High School"
  condition:
  - condition: time
    after: '19:00:00'
  action:
    - service: notify.gmaillolo
      data_template:
        message: 'Div left yoga. ETA: {{states("sensor.div_to_home")}} min.'

- alias: Switch everything off when we leave home
  initial_state: false
  trigger:
    - platform: state
      entity_id: person.div
      from: "home"
    - platform: state
      entity_id: person.laurent
      from: "home"
  condition:
    - condition: template
      value_template: '{{ states("person.laurent") != "home"}}'
    - condition: template
      value_template: '{{ states("person.div") != "home"}}'
  action:
  - service: media_player.turn_off
    entity_id: media_player.kitchen
  - service: media_player.turn_off
    entity_id: media_player.onkyo_tx_nr656
  - service: media_player.turn_off
    entity_id: media_player.conservatory
  - service: media_player.turn_off
    entity_id: media_player.house
  - service: media_player.turn_off
    entity_id: media_player.downstairs
  - service: input_boolean.turn_off
    entity_id: input_boolean.normal
  - service: light.turn_off
    data:
      entity_id: group.Interior_Lights
  - service: light.turn_off
    data:
      entity_id: light.living_room_main
  - service: input_boolean.turn_on
    entity_id: input_boolean.silent
  - service: input_boolean.turn_on
    entity_id: input_boolean.normal
  - service: input_boolean.turn_off
    entity_id: input_boolean.silent



- alias: Tell Lolo of a long drive home
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.lolo_to_home
  condition:
    - condition: time
      after: '15:30:00'
      before: '18:00:00'
      weekday:
        - tue
        - wed
        - thu
    - condition: template
      value_template: '{{ states("sensor.lolo_to_home") |int(0) >= 65 }}'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("automation.tell_lolo_of_a_long_drive_home", "last_triggered") | default(0)) | int > 3600)}}'
    - condition: template
      value_template: '{{ states("person.laurent") == "Verint"}}'
  action:
    - condition: state
      entity_id: input_boolean.silent
      state: "off"
    - service: notify.gmaillolo
      data_template:
        message: 'There is a long drive home ({{states("sensor.lolo_to_home") |int(0)}} min)...'




- alias: location_lolo
  initial_state: true
  trigger:
      - platform: state
        entity_id: person.laurent
  action:
    service: mqtt.publish
    data_template:
      topic: 'location/lolo'
      payload_template: '{{ trigger.to_state.state }}'
      retain: true

- alias: location_div
  initial_state: true
  trigger:
      - platform: state
        entity_id: person.div
  action:
    service: mqtt.publish
    data_template:
      topic: 'location/div'
      payload_template: '{{ trigger.to_state.state }}'
      retain: true