- alias: Tell Div Lolo left work
  trigger:
    platform: zone
    entity_id: device_tracker.lolo
    zone: zone.verint
    event: leave
  condition:
  - condition: time
    after: '16:15:00'
  action:
    service: notify.gmaildiv
    data_template:
      message: 'Lolo left work. Estimated arrival time: {{(as_timestamp(now()) + (states.sensor.lolo_to_home.state | default(0) | int)*60) | timestamp_custom("%H:%M")}}'
  # initial_state: false


- alias: Tell Div Lolo reached work
  trigger:
    platform: zone
    entity_id: device_tracker.lolo
    zone: zone.verint
    event: enter
  condition:
  - condition: time
    before: '10:00:00'
  action:
    service: notify.gmaildiv
    data_template:
      message: 'Lolo reached work.'
  # initial_state: false


- alias: Tell Lolo Div left work
  trigger:
    platform: zone
    entity_id: device_tracker.div
    zone: zone.cbc
    event: leave
  condition:
  - condition: time
    after: '16:30:00'
  action:
    - service: notify.gmaillolo
      data_template:
        message: 'Div left work.'
    - service: tts.google_say
      entity_id: media_player.living_room_google_mini
      data:
        message: 'Please note: Div left work'

- alias: Switch everything off when we leave home
  trigger:
    - platform: zone
      entity_id: device_tracker.div
      zone: zone.home
      event: leave
    - platform: zone
      entity_id: device_tracker.lolo
      zone: zone.home
      event: leave
  condition:
    - condition: template
      value_template: '{{ states.device_tracker.lolo.state != "home"}}'
    - condition: template
      value_template: '{{ states.device_tracker.div.state != "home"}}'
  action:
  - service: media_player.turn_off
    entity_id: media_player.kitchen
  - service: media_player.turn_off
    entity_id: media_player.onkyo_txnr656
  - service: media_player.turn_off
    entity_id: media_player.bedroom
  - service: media_player.turn_off
    entity_id: media_player.house
  - service: media_player.turn_off
    entity_id: media_player.downstairs
  - service: light.turn_off
    data:
      entity_id: group.Interior_Lights



- alias: Tell Lolo to leave for work
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 0
  condition:
    - condition: time
      before: '08:00:00'
      weekday:
        - tue
        - wed
        - thu
    - condition: template
      value_template: '{{ (as_timestamp(now().strftime("%Y-%m-%d") + " 08:30")  - states.sensor.home_to_verint.attributes.duration.split(" ")[0] | int *60 )  <=  (as_timestamp(now())) }}'
    - condition: template
      value_template: '{{ states.device_tracker.lolo.state == "home"}}'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.tell_lolo_to_leave_for_work.attributes.last_triggered | default(0)) | int > 3600)}}'
  action:
    - service: tts.google_say
      entity_id: media_player.living_room_google_mini
      data:
        message: "Hey lo lo, it's time to leave for work..."



- alias: Tell Lolo of a long drive home
  trigger:
    - platform: state
      entity_id: sensor.lolo_to_home
  condition:
    - condition: time
      after: '16:30:00'
      before: '18:00:00'
      weekday:
        - tue
        - wed
        - thu
    - condition: template
      value_template: '{{ states.sensor.lolo_to_home.state |int(0) >= 65 }}'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.tell_lolo_of_a_long_drive_home.attributes.last_triggered | default(0)) | int > 3600)}}'
    - condition: template
      value_template: '{{ states.device_tracker.lolo.state == "Verint"}}'
  action:
    - service: notify.gmaillolo
      data_template:
        message: 'There is a long drive home ({{states.sensor.lolo_to_home.state |int(0)}} min)...'

- alias: location_lolo
  trigger:
      - platform: state
        entity_id: 'device_tracker.lolos_iphone'
      - platform: state
        entity_id: 'device_tracker.ha_lolos_iphone'
  action:
    service: mqtt.publish
    data_template:
      topic: 'location/lolo'
      payload_template: '{{ trigger.to_state.state }}'
      retain: true

- alias: location_div
  trigger:
      - platform: state
        entity_id: 'device_tracker.div_iphone'
      - platform: state
        entity_id: 'device_tracker.ha_div_iphone'
  action:
    service: mqtt.publish
    data_template:
      topic: 'location/div'
      payload_template: '{{ trigger.to_state.state }}'
      retain: true