- alias: Tell Div Lolo left work
  trigger:
    platform: state
    entity_id: device_tracker.lolo
    from: "Verint"
  condition:
  - condition: time
    after: '15:30:00'
  action:
    service: notify.gmaildiv
    data_template:
      message: 'Lolo left work. Estimated arrival time: {{(as_timestamp(now()) + (states.sensor.lolo_to_home.state | default(0) | int)*60) | timestamp_custom("%H:%M")}}'



- alias: Tell Div Lolo reached work
  trigger:
    platform: state
    entity_id: device_tracker.lolo
    to: "Verint"
  condition:
  - condition: time
    before: '10:00:00'
  action:
    service: notify.gmaildiv
    data_template:
      message: 'Lolo reached work.'


- alias: Tell Lolo Div left work
  trigger:
    platform: state
    entity_id: device_tracker.div
    from: "CBC"
  condition:
  - condition: time
    after: '16:30:00'
  action:
    - service: notify.gmaillolo
      data_template:
        message: 'Div left work.'
    - condition: state
      entity_id: input_boolean.silent
      state: "off"
    - service: tts.google_say
      entity_id: media_player.google_home_minis
      data:
        message: 'Please note: Div left work'

- alias: Switch everything off when we leave home
  trigger:
    - platform: state
      entity_id: device_tracker.div
      from: "home"
    - platform: state
      entity_id: device_tracker.lolo
      from: "home"
  condition:
    - condition: template
      value_template: '{{ states.device_tracker.lolo.state != "home"}}'
    - condition: template
      value_template: '{{ states.device_tracker.div.state != "home"}}'
  action:
  - service: media_player.turn_off
    entity_id: media_player.kitchen
  - service: media_player.turn_off
    entity_id: media_player.onkyo_txnr656
  - service: media_player.turn_off
    entity_id: media_player.conservatory
  - service: media_player.turn_off
    entity_id: media_player.house
  - service: media_player.turn_off
    entity_id: media_player.downstairs
  - service: light.turn_off
    data:
      entity_id: group.Interior_Lights



# - alias: Tell Lolo to leave for work
  # trigger:
    # - platform: time
      # minutes: '/1'
      # seconds: 0
  # condition:
    # - condition: time
      # before: '08:00:00'
      # weekday:
        # - tue
        # - wed
        # - thu
    # - condition: template
      # value_template: '{{ (as_timestamp(now().strftime("%Y-%m-%d") + " 08:30")  - states.sensor.home_to_work.attributes.duration.split(" ")[0] | int *60 )  <=  (as_timestamp(now())) }}'
    # - condition: template
      # value_template: '{{ states.device_tracker.lolo.state == "home"}}'
    # - condition: template
      # value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.tell_lolo_to_leave_for_work.attributes.last_triggered | default(0)) | int > 3600)}}'
  # action:
    # - service: tts.google_say
      # entity_id: media_player.google_home_minis
      # data:
        # message: "Hey lo lo, it's time to leave for work..."



- alias: Tell Lolo of a long drive home
  trigger:
    - platform: state
      entity_id: sensor.lolo_to_home
  condition:
    - condition: time
      after: '15:30:00'
      before: '18:00:00'
      weekday:
        - tue
        - wed
        - thu
    - condition: template
      value_template: '{{ states.sensor.lolo_to_home.state |int(0) >= 65 }}'
    - condition: template
      value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.tell_lolo_of_a_long_drive_home.attributes.last_triggered | default(0)) | int > 3600)}}'
    - condition: template
      value_template: '{{ states.device_tracker.lolo.state == "Verint"}}'
  action:
    - condition: state
      entity_id: input_boolean.silent
      state: "off"
    - service: notify.gmaillolo
      data_template:
        message: 'There is a long drive home ({{states.sensor.lolo_to_home.state |int(0)}} min)...'




- alias: location_lolo
  trigger:
      - platform: state
        entity_id: 'device_tracker.lolos_iphone'
      - platform: state
        entity_id: 'device_tracker.ha_lolos_iphone'
      - platform: state
        entity_id: 'device_tracker.google_maps_110345542315981072615'
      - platform: state
        entity_id: 'device_tracker.laurent_mah_iphone_5s'
  action:
    service: mqtt.publish
    data_template:
      topic: 'location/lolo'
      payload_template: '{{ trigger.to_state.state }}'
      #payload_template: '{"lat":"{{- trigger.to_state.attributes.latitude -}}","lon":"{{- trigger.to_state.lolos_iphone.attributes.longitude -}}"}'
      retain: true

- alias: location_div
  trigger:
      - platform: state
        entity_id: 'device_tracker.div_iphone'
      - platform: state
        entity_id: 'device_tracker.ha_div_iphone'
      - platform: state
        entity_id: 'device_tracker.google_maps_113578038090869627198'
  action:
    service: mqtt.publish
    data_template:
      topic: 'location/div'
      payload_template: '{{ trigger.to_state.state }}'
      retain: true

# {%- for attribute in states.device_tracker.ha_lolos_iphone.attributes -%}
# {%- if attribute == "latitude" or attribute == "longitude"  or attribute == "battery" -%}
# "{{attribute}}":"{{state_attr('device_tracker.ha_lolos_iphone',attribute)}}", 
# {%- endif %} {%- endfor %}"friendly_name":"Lolo", "entity_picture":"/local/Lolo_Avatar.jpg"