- alias: Ram too high
  trigger:
    - platform: numeric_state
      entity_id: sensor.ram_usage
      value_template: '{{ state.attributes.status }}'
      above: 90
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.automation.ram_too_high.attributes.last_triggered) | int > 3600 )}}'
  action:
    - service: notify.gmaillolo
      data_template:
        message: 'RAM is above 90% ({{states.sensor.ram_usage.state}}%)'

- alias: Free Ram
  trigger:
    - platform: numeric_state
      entity_id: sensor.ram_usage
      value_template: '{{ state.attributes.status }}'
      above: 70
  condition:
    - condition: template
      value_template: '{{(as_timestamp(now()) - as_timestamp(states.automation.ram_too_high.attributes.last_triggered) | int > 3600 )}}'
  action:
    - service: shell_command.freeram