- alias: Switch Onkyo and Viera Off at 02:00
  trigger:
    platform: time
    hours: 2
    minutes: 0
    seconds: 0
  action:
  - service: media_player.turn_off
    entity_id: media_player.onkyo_txnr656
  - service: media_player.turn_off
    entity_id: media_player.panasonic_viera_tv