- alias: Xmas Lights On
  initial_state: true
  trigger:
    - platform: state
      entity_id: 
        - binary_sensor.pir_conservatory
        - binary_sensor.pir_kitchen
        - binary_sensor.pir_living_room_front
        - binary_sensor.pir_living_room_back
        - binary_sensor.pir_staircase
      to: 'on'
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
    - platform: state
      entity_id: binary_sensor.photoresistor
      to: 'off'
    - platform: state
      entity_id: sensor.aloe_vera_light_intensity
  condition:
    - condition: state
      entity_id: input_boolean.xmas
      state: 'on'
    - condition: state
      entity_id: input_boolean.normal
      state: 'on'
    - condition: state
      entity_id: group.pirs
      state: 'on'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.lwrf_socket_xmas
  - service: light.turn_on
    data:
      entity_id: light.TV_Cabinet_LED_Strip
      brightness: 255
      effect: colorfade_fast
  - service: light.turn_on
    data:
      entity_id: light.Staircase_LED_Strip
      brightness: 255
      effect: colorfade_fast
  - service: light.turn_on
    data:
      entity_id: group.baubles
  - service: light.turn_on
    data:
      entity_id: light.conservatory_led_strip
      effect: "rainbow"
      brightness: 255
  - service: light.turn_on
    data:
      entity_id: light.conservatory_led_strip
      effect: "rainbow"
      brightness: 255
  - service: switch.turn_on
    data:
      entity_id: switch.edimax1
  - service: light.turn_on
    data:
      entity_id: group.xmas




- alias: Xmas Lights Off
  initial_state: true
  trigger:
    - platform: state
      entity_id: group.pirs
      to: 'off'
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: input_boolean.xmas
      state: 'on'
    - condition: state
      entity_id: media_player.panasonic_viera_tv
      state: 'off'
  action:
  - service: light.turn_off
    data:
      entity_id: group.xmas
  - service: light.turn_off
    data:
      entity_id: light.Staircase_LED_Strip
  - service: light.turn_off
    data:
      entity_id: light.TV_Cabinet_LED_Strip
  - service: switch.turn_off
    data:
      entity_id: switch.lwrf_socket_xmas
  - service: light.turn_off
    data:
      entity_id: light.conservatory_led_strip
  - service: switch.turn_off
    data:
      entity_id: switch.edimax1
  - service: light.turn_off
    data:
      entity_id: group.xmas




