- alias: Tell Div Lolo reached work
  trigger:
    platform: zone
    entity_id: device_tracker.zevsmpjl_lolo_iphone
    zone: zone.verint
    event: enter
  condition:
  - condition: time
    before: '10:00:00'
  action:
    service: notify.gmaildiv
    data_template:
      message: 'Lolo reached work.'
  # initial_state: false



# - alias: Tell Div Lolo reached work2
  # trigger:
    # platform: state
    # entity_id: device_tracker.zevsmpjl_lolo_iphone
    # from: 'not_home'
    # to: 'verint'
  # condition:
  # - condition: time
    # before: '10:00:00'
  # action:
    # service: notify.gmaildiv
    # data_template:
      # message: 'Lolo reached work.'