- alias: Tell Lolo Div left work
  trigger:
    platform: zone
    entity_id: device_tracker.zevsmpjl_div_iphone
    zone: zone.cbc
    event: leave
  condition:
  - condition: time
    after: '16:30:00'
  action:
    service: notify.gmaillolo
    data_template:
      message: 'Div left work.'



# - alias: Tell Lolo Div left work2
  # trigger:
    # platform: state
    # entity_id: device_tracker.zevsmpjl_div_iphone
    # from: 'cbc'
  # condition:
  # - condition: time
    # after: '17:00:00'
  # action:
    # service: notify.gmaillolo
    # data_template:
      # message: 'Div left work.'