- alias: Tell Div Lolo left work
  trigger:
    platform: zone
    entity_id: device_tracker.zevsmpjl_lolo_iphone
    zone: zone.verint
    event: leave
  condition:
  - condition: time
    after: '16:15:00'
  action:
    service: notify.gmaildiv
    data_template:
      message: 'Lolo left work. Estimated arrival time: {{(as_timestamp(now()) + (states.sensor.lolo_to_home.state | int)*60) | timestamp_custom("%H:%M")}}'
  # initial_state: false



# - alias: Tell Div Lolo left work2
  # trigger:
    # platform: state
    # entity_id: device_tracker.zevsmpjl_lolo_iphone
    # from: 'verint'
    # to: 'not_home'
  # condition:
  # - condition: time
    # after: '16:15:00'
  # action:
    # service: notify.gmaildiv
    # data_template:
      # message: 'Lolo left work. Estimated drive time: {{states.sensor.lolo_to_home.state}} min'
